#if !defined(AFX_NODES_H__3BBDBDA1_2C62_45C7_87E3_773178776695__INCLUDED_)
#define AFX_NODES_H__3BBDBDA1_2C62_45C7_87E3_773178776695__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CNode;

/////////////////////////////////////////////////////////////////////////////
// CNodes wrapper class

class CNodes : public COleDispatchDriver
{
public:
	CNodes() {}		// Calls COleDispatchDriver default constructor
	CNodes(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CNodes(const CNodes& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	short GetCount();
	void SetCount(short nNewValue);
	CNode Add(VARIANT* Relative, VARIANT* Relationship, VARIANT* Key, VARIANT* Text, VARIANT* Image, VARIANT* SelectedImage);
	void Clear();
	CNode GetItem(VARIANT* Index);
	void SetItem(VARIANT* Index, LPDISPATCH newValue);
	void Remove(VARIANT* Index);
	LPDISPATCH _NewEnum();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NODES_H__3BBDBDA1_2C62_45C7_87E3_773178776695__INCLUDED_)
