// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "oleobjects.h"

// Dispatch interfaces referenced by this interface
#include "oleobject.h"


/////////////////////////////////////////////////////////////////////////////
// COLEObjects properties

/////////////////////////////////////////////////////////////////////////////
// COLEObjects operations

COLEObject COLEObjects::GetItem(const VARIANT& Item)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		&Item);
	return COLEObject(pDispatch);
}

long COLEObjects::GetCount()
{
	long result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void COLEObjects::Clear()
{
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

COLEObject COLEObjects::Add(const VARIANT& Index, const VARIANT& Key, const VARIANT& source, const VARIANT& objclass)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&Index, &Key, &source, &objclass);
	return COLEObject(pDispatch);
}

void COLEObjects::Remove(const VARIANT& Item)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &Item);
}
