#if !defined(AFX_TREEVIEW_H__4B3EC5AD_D4EA_4674_8D13_B2327332E12E__INCLUDED_)
#define AFX_TREEVIEW_H__4B3EC5AD_D4EA_4674_8D13_B2327332E12E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CNode;
class CPicture;
class CNodes;
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CTreeView1 wrapper class

class CTreeView1 : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTreeView1)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xc74190b6, 0x8589, 0x11d1, { 0xb1, 0x6a, 0x0, 0xc0, 0xf0, 0x28, 0x36, 0x28 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	CNode GetDropHighlight();
	void SetRefDropHighlight(LPDISPATCH newValue);
	void SetDropHighlight(VARIANT* newValue);
	BOOL GetHideSelection();
	void SetHideSelection(BOOL bNewValue);
	LPDISPATCH GetImageList();
	void SetRefImageList(LPDISPATCH newValue);
	void SetImageList(LPDISPATCH newValue);
	float GetIndentation();
	void SetIndentation(float newValue);
	long GetLabelEdit();
	void SetLabelEdit(long nNewValue);
	long GetLineStyle();
	void SetLineStyle(long nNewValue);
	long GetMousePointer();
	void SetMousePointer(long nNewValue);
	CPicture GetMouseIcon();
	void SetMouseIcon(LPDISPATCH newValue);
	void SetRefMouseIcon(LPDISPATCH newValue);
	CNodes GetNodes();
	void SetRefNodes(LPDISPATCH newValue);
	CString GetPathSeparator();
	void SetPathSeparator(LPCTSTR lpszNewValue);
	CNode GetSelectedItem();
	void SetRefSelectedItem(LPDISPATCH newValue);
	void SetSelectedItem(VARIANT* newValue);
	BOOL GetSorted();
	void SetSorted(BOOL bNewValue);
	long GetStyle();
	void SetStyle(long nNewValue);
	long GetOLEDragMode();
	void SetOLEDragMode(long nNewValue);
	long GetOLEDropMode();
	void SetOLEDropMode(long nNewValue);
	long GetAppearance();
	void SetAppearance(long nNewValue);
	long GetBorderStyle();
	void SetBorderStyle(long nNewValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	COleFont GetFont();
	void SetFont(LPDISPATCH newValue);
	void SetRefFont(LPDISPATCH newValue);
	long GetHWnd();
	void SetHWnd(long nNewValue);
	CNode HitTest(float x, float y);
	long GetVisibleCount();
	void StartLabelEdit();
	void Refresh();
	void OLEDrag();
	BOOL GetCheckboxes();
	void SetCheckboxes(BOOL bNewValue);
	BOOL GetFullRowSelect();
	void SetFullRowSelect(BOOL bNewValue);
	BOOL GetHotTracking();
	void SetHotTracking(BOOL bNewValue);
	BOOL GetScroll();
	void SetScroll(BOOL bNewValue);
	BOOL GetSingleSel();
	void SetSingleSel(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TREEVIEW_H__4B3EC5AD_D4EA_4674_8D13_B2327332E12E__INCLUDED_)
