FileTableEntry gFileCacheTable[] =
{
	{"COMMON.ST2", fcsNotCached, 0},
	{"FRONTEND.ST2", fcsNotCached, 0},
	{"GAME.INI", fcsNotCached, 0},
	{"LEGAL.ST2", fcsNotCached, 0},
	{"NSLDSP.BIN", fcsNotCached, 0},
	{"SYSTEM.ST2", fcsNotCached, 0},
	// C:\ks\DISKIMG\beaches
	{"ANTARCTI.ST2", fcsNotCached, 1},
	{"BELLS.ST2", fcsNotCached, 1},
	{"BELLSNIG.ST2", fcsNotCached, 1},
	{"CORTESBA.ST2", fcsNotCached, 1},
	{"COSMOS.ST2", fcsNotCached, 1},
	{"CURRENSP.ST2", fcsNotCached, 1},
	{"GLAND.ST2", fcsNotCached, 1},
	{"GLAND2.ST2", fcsNotCached, 1},
	{"INDOOR.ST2", fcsNotCached, 1},
	{"JAWS.ST2", fcsNotCached, 1},
	{"JAWSBIG.ST2", fcsNotCached, 1},
	{"JEFFERSO.ST2", fcsNotCached, 1},
	{"KIRRA.ST2", fcsNotCached, 1},
	{"KIRRA2.ST2", fcsNotCached, 1},
	{"MAVBIG.ST2", fcsNotCached, 1},
	{"MAVERICK.ST2", fcsNotCached, 1},
	{"MUNDAKA.ST2", fcsNotCached, 1},
	{"MUNDAKA2.ST2", fcsNotCached, 1},
	{"OPENSEA.ST2", fcsNotCached, 1},
	{"PIPELINE.ST2", fcsNotCached, 1},
	{"SEBASTIA.ST2", fcsNotCached, 1},
	{"TEAEVE.ST2", fcsNotCached, 1},
	{"TEAHUPOO.ST2", fcsNotCached, 1},
	{"TEANIGHT.ST2", fcsNotCached, 1},
	{"TRESTLES.ST2", fcsNotCached, 1},
	// C:\ks\DISKIMG\challeng
	{"ANTLEV1.ST2", fcsNotCached, 2},
	{"ANTLEV2.ST2", fcsNotCached, 2},
	{"BELLLEV1.ST2", fcsNotCached, 2},
	{"CURRLEV1.ST2", fcsNotCached, 2},
	{"GLANLEV1.ST2", fcsNotCached, 2},
	{"ICON.ST2", fcsNotCached, 2},
	{"JAWSLEV2.ST2", fcsNotCached, 2},
	{"JEFFLEV1.ST2", fcsNotCached, 2},
	{"JEFFLEV2.ST2", fcsNotCached, 2},
	{"KIRRLEV1.ST2", fcsNotCached, 2},
	{"KIRRLEV2.ST2", fcsNotCached, 2},
	{"MAVLEV1.ST2", fcsNotCached, 2},
	{"MAVLEV2.ST2", fcsNotCached, 2},
	{"MUNDLEV1.ST2", fcsNotCached, 2},
	{"MUNDLEV2.ST2", fcsNotCached, 2},
	{"PIPELEV1.ST2", fcsNotCached, 2},
	{"PIPELEV2.ST2", fcsNotCached, 2},
	{"SEBLEV1.ST2", fcsNotCached, 2},
	{"SEBLEV2.ST2", fcsNotCached, 2},
	{"TEALEV1.ST2", fcsNotCached, 2},
	{"TEALEV2.ST2", fcsNotCached, 2},
	{"TRESLEV1.ST2", fcsNotCached, 2},
	{"TRESLEV2.ST2", fcsNotCached, 2},
	// C:\ks\DISKIMG\DEMOS
	{"REPLAY0.RPL", fcsNotCached, 3},
	{"REPLAY4.RPL", fcsNotCached, 3},
	{"REPLAY8.RPL", fcsNotCached, 3},
	// C:\ks\DISKIMG\levels
	// C:\ks\DISKIMG\surfers
	{"BRUCEIRO.ST2", fcsNotCached, 5},
	{"FRANKENR.ST2", fcsNotCached, 5},
	{"KALANIRO.ST2", fcsNotCached, 5},
	{"KELLYSLA.ST2", fcsNotCached, 5},
	{"LISAANDE.ST2", fcsNotCached, 5},
	{"MISCSURF.ST2", fcsNotCached, 5},
	{"NATHANFL.ST2", fcsNotCached, 5},
	{"PERSONBI.ST2", fcsNotCached, 5},
	{"PERSONDF.ST2", fcsNotCached, 5},
	{"PERSONKR.ST2", fcsNotCached, 5},
	{"PERSONKS.ST2", fcsNotCached, 5},
	{"PERSONLA.ST2", fcsNotCached, 5},
	{"PERSONMS.ST2", fcsNotCached, 5},
	{"PERSONNF.ST2", fcsNotCached, 5},
	{"PERSONRM.ST2", fcsNotCached, 5},
	{"PERSONTA.ST2", fcsNotCached, 5},
	{"PERSONTU.ST2", fcsNotCached, 5},
	{"ROBMACHA.ST2", fcsNotCached, 5},
	{"SURFREAK.ST2", fcsNotCached, 5},
	{"TIKIGOD.ST2", fcsNotCached, 5},
	{"TOMCARRO.ST2", fcsNotCached, 5},
	{"TOMCURRE.ST2", fcsNotCached, 5},
	{"TONYHAWK.ST2", fcsNotCached, 5},
	{"TRAVISPA.ST2", fcsNotCached, 5},
	// C:\ks\DISKIMG\surfers\auxstash
	// C:\ks\DISKIMG\surfers\bchbrd
	{"ANTA_BRD.ST2", fcsNotCached, 7},
	{"BELL_BRD.ST2", fcsNotCached, 7},
	{"CORT_BRD.ST2", fcsNotCached, 7},
	{"COSM_BRD.ST2", fcsNotCached, 7},
	{"CURR_BRD.ST2", fcsNotCached, 7},
	{"GLAN_BRD.ST2", fcsNotCached, 7},
	{"JAWS_BRD.ST2", fcsNotCached, 7},
	{"JEFF_BRD.ST2", fcsNotCached, 7},
	{"KIRR_BRD.ST2", fcsNotCached, 7},
	{"MAVE_BRD.ST2", fcsNotCached, 7},
	{"MUND_BRD.ST2", fcsNotCached, 7},
	{"PIPE_BRD.ST2", fcsNotCached, 7},
	{"SEBA_BRD.ST2", fcsNotCached, 7},
	{"TEAH_BRD.ST2", fcsNotCached, 7},
	{"TRES_BRD.ST2", fcsNotCached, 7},
	// C:\ks\DISKIMG\surfers\auxstash\bruceiro
	{"BIP_AUX.ST2", fcsNotCached, 8},
	{"BIP_BRD.ST2", fcsNotCached, 8},
	{"BI_0_BRD.ST2", fcsNotCached, 8},
	{"BI_1_BRD.ST2", fcsNotCached, 8},
	{"BI_2_BRD.ST2", fcsNotCached, 8},
	{"BI_3_BRD.ST2", fcsNotCached, 8},
	{"BI_4_BRD.ST2", fcsNotCached, 8},
	{"BI_5_BRD.ST2", fcsNotCached, 8},
	{"BI_6_BRD.ST2", fcsNotCached, 8},
	{"BI_7_BRD.ST2", fcsNotCached, 8},
	{"BI_8_BRD.ST2", fcsNotCached, 8},
	{"BI_AUX.ST2", fcsNotCached, 8},
	// C:\ks\DISKIMG\surfers\auxstash\frankenr
	{"DFP_AUX.ST2", fcsNotCached, 9},
	{"DFP_BRD.ST2", fcsNotCached, 9},
	{"DF_0_BRD.ST2", fcsNotCached, 9},
	{"DF_1_BRD.ST2", fcsNotCached, 9},
	{"DF_2_BRD.ST2", fcsNotCached, 9},
	{"DF_3_BRD.ST2", fcsNotCached, 9},
	{"DF_4_BRD.ST2", fcsNotCached, 9},
	{"DF_5_BRD.ST2", fcsNotCached, 9},
	{"DF_6_BRD.ST2", fcsNotCached, 9},
	{"DF_7_BRD.ST2", fcsNotCached, 9},
	{"DF_8_BRD.ST2", fcsNotCached, 9},
	{"DF_AUX.ST2", fcsNotCached, 9},
	// C:\ks\DISKIMG\surfers\auxstash\kalaniro
	{"KRP_AUX.ST2", fcsNotCached, 10},
	{"KRP_BRD.ST2", fcsNotCached, 10},
	{"KR_0_BRD.ST2", fcsNotCached, 10},
	{"KR_1_BRD.ST2", fcsNotCached, 10},
	{"KR_2_BRD.ST2", fcsNotCached, 10},
	{"KR_3_BRD.ST2", fcsNotCached, 10},
	{"KR_4_BRD.ST2", fcsNotCached, 10},
	{"KR_5_BRD.ST2", fcsNotCached, 10},
	{"KR_6_BRD.ST2", fcsNotCached, 10},
	{"KR_7_BRD.ST2", fcsNotCached, 10},
	{"KR_8_BRD.ST2", fcsNotCached, 10},
	{"KR_AUX.ST2", fcsNotCached, 10},
	// C:\ks\DISKIMG\surfers\auxstash\kellysla
	{"KSP_AUX.ST2", fcsNotCached, 11},
	{"KSP_BRD.ST2", fcsNotCached, 11},
	{"KS_0_BRD.ST2", fcsNotCached, 11},
	{"KS_1_BRD.ST2", fcsNotCached, 11},
	{"KS_2_BRD.ST2", fcsNotCached, 11},
	{"KS_3_BRD.ST2", fcsNotCached, 11},
	{"KS_4_BRD.ST2", fcsNotCached, 11},
	{"KS_5_BRD.ST2", fcsNotCached, 11},
	{"KS_6_BRD.ST2", fcsNotCached, 11},
	{"KS_7_BRD.ST2", fcsNotCached, 11},
	{"KS_8_BRD.ST2", fcsNotCached, 11},
	{"KS_AUX.ST2", fcsNotCached, 11},
	// C:\ks\DISKIMG\surfers\auxstash\lisaande
	{"LAP_AUX.ST2", fcsNotCached, 12},
	{"LAP_BRD.ST2", fcsNotCached, 12},
	{"LA_0_BRD.ST2", fcsNotCached, 12},
	{"LA_1_BRD.ST2", fcsNotCached, 12},
	{"LA_2_BRD.ST2", fcsNotCached, 12},
	{"LA_3_BRD.ST2", fcsNotCached, 12},
	{"LA_4_BRD.ST2", fcsNotCached, 12},
	{"LA_5_BRD.ST2", fcsNotCached, 12},
	{"LA_6_BRD.ST2", fcsNotCached, 12},
	{"LA_7_BRD.ST2", fcsNotCached, 12},
	{"LA_8_BRD.ST2", fcsNotCached, 12},
	{"LA_AUX.ST2", fcsNotCached, 12},
	// C:\ks\DISKIMG\surfers\auxstash\miscsurf
	{"MS_0_BRD.ST2", fcsNotCached, 13},
	{"MS_AUX.ST2", fcsNotCached, 13},
	// C:\ks\DISKIMG\surfers\auxstash\nathanfl
	{"NFP_AUX.ST2", fcsNotCached, 14},
	{"NFP_BRD.ST2", fcsNotCached, 14},
	{"NF_0_BRD.ST2", fcsNotCached, 14},
	{"NF_1_BRD.ST2", fcsNotCached, 14},
	{"NF_2_BRD.ST2", fcsNotCached, 14},
	{"NF_3_BRD.ST2", fcsNotCached, 14},
	{"NF_4_BRD.ST2", fcsNotCached, 14},
	{"NF_5_BRD.ST2", fcsNotCached, 14},
	{"NF_6_BRD.ST2", fcsNotCached, 14},
	{"NF_7_BRD.ST2", fcsNotCached, 14},
	{"NF_8_BRD.ST2", fcsNotCached, 14},
	{"NF_AUX.ST2", fcsNotCached, 14},
	// C:\ks\DISKIMG\surfers\auxstash\robmacha
	{"RMP_AUX.ST2", fcsNotCached, 15},
	{"RMP_BRD.ST2", fcsNotCached, 15},
	{"RM_0_BRD.ST2", fcsNotCached, 15},
	{"RM_1_BRD.ST2", fcsNotCached, 15},
	{"RM_2_BRD.ST2", fcsNotCached, 15},
	{"RM_3_BRD.ST2", fcsNotCached, 15},
	{"RM_4_BRD.ST2", fcsNotCached, 15},
	{"RM_5_BRD.ST2", fcsNotCached, 15},
	{"RM_6_BRD.ST2", fcsNotCached, 15},
	{"RM_7_BRD.ST2", fcsNotCached, 15},
	{"RM_8_BRD.ST2", fcsNotCached, 15},
	{"RM_AUX.ST2", fcsNotCached, 15},
	// C:\ks\DISKIMG\surfers\auxstash\surfreak
	{"SF_0_BRD.ST2", fcsNotCached, 16},
	{"SF_AUX.ST2", fcsNotCached, 16},
	// C:\ks\DISKIMG\surfers\auxstash\tikigod
	{"TG_0_BRD.ST2", fcsNotCached, 17},
	{"TG_AUX.ST2", fcsNotCached, 17},
	// C:\ks\DISKIMG\surfers\auxstash\tomcarro
	{"TAP_AUX.ST2", fcsNotCached, 18},
	{"TAP_BRD.ST2", fcsNotCached, 18},
	{"TA_0_BRD.ST2", fcsNotCached, 18},
	{"TA_1_BRD.ST2", fcsNotCached, 18},
	{"TA_2_BRD.ST2", fcsNotCached, 18},
	{"TA_3_BRD.ST2", fcsNotCached, 18},
	{"TA_4_BRD.ST2", fcsNotCached, 18},
	{"TA_5_BRD.ST2", fcsNotCached, 18},
	{"TA_6_BRD.ST2", fcsNotCached, 18},
	{"TA_7_BRD.ST2", fcsNotCached, 18},
	{"TA_8_BRD.ST2", fcsNotCached, 18},
	{"TA_AUX.ST2", fcsNotCached, 18},
	// C:\ks\DISKIMG\surfers\auxstash\tomcurre
	{"TUP_AUX.ST2", fcsNotCached, 19},
	{"TUP_BRD.ST2", fcsNotCached, 19},
	{"TU_0_BRD.ST2", fcsNotCached, 19},
	{"TU_1_BRD.ST2", fcsNotCached, 19},
	{"TU_2_BRD.ST2", fcsNotCached, 19},
	{"TU_3_BRD.ST2", fcsNotCached, 19},
	{"TU_4_BRD.ST2", fcsNotCached, 19},
	{"TU_5_BRD.ST2", fcsNotCached, 19},
	{"TU_6_BRD.ST2", fcsNotCached, 19},
	{"TU_7_BRD.ST2", fcsNotCached, 19},
	{"TU_8_BRD.ST2", fcsNotCached, 19},
	{"TU_AUX.ST2", fcsNotCached, 19},
	// C:\ks\DISKIMG\surfers\auxstash\tonyhawk
	{"TH_0_BRD.ST2", fcsNotCached, 20},
	{"TH_AUX.ST2", fcsNotCached, 20},
	// C:\ks\DISKIMG\surfers\auxstash\travispa
	{"TP_0_BRD.ST2", fcsNotCached, 21},
	{"TP_AUX.ST2", fcsNotCached, 21},
};
