// this file provides preset anim_ids for our NEW biped skeletons;
// the numeric values correspond to our old preset anim ids (see anim_ids.h)
MAC( PELVIS,      0 )
MAC( R_THIGH,     1 )
MAC( R_CALF,      2 )
MAC( R_FOOT,      3 )
MAC( R_TOE0,      4 )
MAC( L_THIGH,     5 )
MAC( L_CALF,      6 )
MAC( L_FOOT,      7 )
MAC( L_TOE0,      8 )
MAC( SPINE1,      9 )
MAC( SPINE2,     10 )
MAC( R_CLAVICLE, 11 )
MAC( R_UPPERARM, 12 )
MAC( R_FOREARM,  13 )
MAC( R_HAND,     14 )
MAC( L_CLAVICLE, 15 )
MAC( L_UPPERARM, 16 )
MAC( L_FOREARM,  17 )
MAC( L_HAND,     18 )
MAC( NECK,       19 )
MAC( HEAD,       20 )
