#ifndef COMMANDS_HEADER
#define COMMANDS_HEADER
////////////////////////////////////////////////////////////////////////////////
/*
  commands.h

  Big list of game commands.  Look in game.cpp for their keyboard mappings.
*/
////////////////////////////////////////////////////////////////////////////////


enum game_control_t
{
  /////////////////////////////////////////////////////////////////////////////
  // These values are used (under the same names) by the script library (d2lib.sh)
  // don't touch them unless you know what you're doing!
  BUTTON_A,
  BUTTON_B,
  BUTTON_X,
  BUTTON_Y,
  DIR_UPDOWN,
  DIR_LEFTRIGHT,
  /////////////////////////////////////////////////////////////////////////////
  
  // Player control
  PLAYER_ATTACK,
  PLAYER_SHOOT,
  PLAYER_FORWARD_AXIS,
  PLAYER_TURN_AXIS,
  PLAYER_ALT_FORWARD_AXIS,
  PLAYER_ALT_TURN_AXIS,
  PLAYER_FORWARD,
  PLAYER_BACKWARD,
  PLAYER_TURN_LEFT,
  PLAYER_TURN_RIGHT,
  PLAYER_STRAFE_LEFT,
  PLAYER_STRAFE_RIGHT,
  PLAYER_BURST_LEFT,
  PLAYER_BURST_RIGHT,
  PLAYER_BURST_FORWARD,
  PLAYER_BURST_BACKWARD,
  PLAYER_BLOCK_LOW,
  PLAYER_BLOCK_HIGH,
  PLAYER_JUMP,
  PLAYER_CROUCH,
  PLAYER_FRONT_CROUCH,
  PLAYER_REAR_CROUCH,
  PLAYER_RESET_POSITION,
  PLAYER_FULL_HEAL,
  PLAYER_ALL_HEAL,
  PLAYER_MUKOR,
  PLAYER_NEXT_ITEM,
  PLAYER_USE_ITEM,
  PLAYER_ACTION,
  PLAYER_MOUSELOOK_MOD,
  PLAYER_STRAFE_MOD,
  PLAYER_VSIM_HIGH,
  PLAYER_VSIM_LOW,
  PLAYER_VSIM_LEFT,
  PLAYER_VSIM_RIGHT,
  PLAYER_VSIM_HIGH_RIGHT,
  PLAYER_VSIM_LOW_RIGHT,
  PLAYER_VSIM_HIGH_LEFT,
  PLAYER_VSIM_LOW_LEFT,
  PLAYER_VSIM_EXTEND,
  PLAYER_VSIM_THRUST_MODE,
  PLAYER_VSIM_FREE_MODE,
  PLAYER_VSIM_SWORD_FLIP,
  PLAYER_WALK_MODE,
  PLAYER_HEAD_CONTROL_MODE,
  PLAYER_HEAD_THETA,
  PLAYER_HEAD_PSI,
  PLAYER_HEAD_LEVEL,
  PLAYER_HEAD_EXTEND,
  PLAYER_JAW_OPEN,
  PLAYER_ARM_CYCLE,
  PLAYER_TAIL_MOD,
  PLAYER_FLIP,
  PLAYER_FLY_TOGGLE,
  PLAYER_SPIN_SWORD,

  // Physics control
  GRAVITY_TOGGLE,
  KILL_VELOCITIES,
  STOP_PHYSICS,
  SINGLE_STEP,

  // Debug info control
  SHOW_DEBUG_INFO,  
  SHOW_PROFILE_INFO,  
  OPEN_PROFILE_ENTRY, 
  SCROLL_PROFILE_INFO,
  SHOW_MEMORY_BUDGET,

  // Debug
  TOGGLE_FOG_COLOR_ADJUSTMENTS,
  SELECT_RED_ADJUSTMENTS,
  SELECT_GREEN_ADJUSTMENTS,
  SELECT_BLUE_ADJUSTMENTS,
  SELECT_DISTANCE_ADJUSTMENTS,
  INC_FOG_COLOR,
  DEC_FOG_COLOR,
  
  // User camera control
  TOGGLE_CAMERA_LOCK,
  USERCAM_FORWARD,
  USERCAM_BACKWARD,
  USERCAM_STRAFE_LEFT,
  USERCAM_STRAFE_RIGHT,
  USERCAM_UP,
  USERCAM_DOWN,
  USERCAM_PITCH,
  USERCAM_YAW,
  USERCAM_FAST,
  USERCAM_SLOW,
  USERCAM_SCREEN_SHOT,
  USERCAM_GENERATE_CUBE_MAP, 
  USERCAM_EQUALS_CHASECAM,
  PAD2_USERCAM_FORWARD,
  PAD2_USERCAM_BACKWARD,
  PAD2_USERCAM_STRAFE_LEFT,
  PAD2_USERCAM_STRAFE_RIGHT,
  PAD2_USERCAM_UP,
  PAD2_USERCAM_DOWN,
  PAD2_USERCAM_PITCH,
  PAD2_USERCAM_YAW,
  PAD2_USERCAM_FAST,
  PAD2_USERCAM_SLOW,
  PAD2_USERCAM_EQUALS_CHASECAM,

  // Replay camera control
  REPLAYCAM_ZOOM,
  REPLAYCAM_PITCH,
  REPLAYCAM_YAW,
  REPLAYCAM_FAST,
  REPLAYCAM_SLOW,


  // camera editing
  USERCAM_SAVE1,
  USERCAM_SAVE2,
  USERCAM_SAVE3,
  USERCAM_SAVE4,
  USERCAM_SAVE5,
  USERCAM_SAVE6,
  USERCAM_SAVE7,
  USERCAM_SAVE8,
  USERCAM_SAVE9,
  USERCAM_SAVE0,
  USERCAM_SAVE_GO,
  USERCAM_SAVE_CLEAR,

  // edit camera
  EDITCAM_FORWARD,
  EDITCAM_BACKWARD,
  EDITCAM_STRAFE_LEFT,
  EDITCAM_STRAFE_RIGHT,
  EDITCAM_UP,
  EDITCAM_DOWN,
  EDITCAM_PITCH_UP,
  EDITCAM_PITCH_DOWN, 
  EDITCAM_YAW_LEFT,
  EDITCAM_YAW_RIGHT,
  EDITCAM_FAST,
  EDITCAM_SLOW,
  EDITCAM_USE_MOUSE,

  // Scene analyzer
  TOGGLE_SCENE_ANALYZER,

  // planes viewer
  PLANE_BOUNDS_MOD,
  FIRST_PLANE_ADJUST,
  LAST_PLANE_ADJUST,

  // Misc.
  //DO_MALOR,
  DO_MALOR_NEXT,
  DO_MALOR_PREV,
  RELOAD_PARTICLE_GENERATORS,
  RELOAD_CHARACTER_ATTRIBUTES,
  DUMP_ENTITY_PO,
  TOGGLE_BSP_SPRAY_PAINT,

  // cheats
  CHEAT_MALOR,
  CHEAT_FULL_HEAL,
  CHEAT_GOD_MODE,
  CHEAT_I_WIN,

  CHEAT_SHOW_ERRORS,

  DC_SCREEN_GRAB,

  // Temporary
  QUIT_GAME,

  // Interface stuff
  GAME_PAUSE,
  INTERFACE_BUTTON,

  // Ptreyarch Front End
  PFE_UPDOWN,
  PFE_LEFTRIGHT,
  PFE_A,
  PFE_B,
  PFE_C,
  PFE_X,
  PFE_Y,
  PFE_Z,
  PFE_START,

  // Last Minute Additions
  PLAYER_AUTOMAP_TRIGGER,
  CONFIG_INPUT_PRESS,
  CONFIG_INPUT_UP,
  CONFIG_INPUT_DOWN,
  CONFIG_INPUT_LEFT,
  CONFIG_INPUT_RIGHT,
  CONFIG_INPUT_ABUTTON, // ESC
  CONFIG_INPUT_BBUTTON, // BKSP

  // MAXSTEEL specific
  SHOOT_PUNCH,
  KICK_ZOOMOUT,
  ACTION_ZOOMIN,
  JUMP_CLIMB,
  NANOTECH,
  INVENTORY,
  START_PDA,
  STICK_AXIS_V,
  STICK_AXIS_H,

  ITEM_SWITCH_DEBUG_ON,
  ITEM_SWITCH_AXIS_TYPE,
  ITEM_INC_AXIS,
  ITEM_DEC_AXIS,
  ITEM_ACC_AXIS,

  MOUSE_AXIS_H,
  MOUSE_AXIS_V,

  PSX_X,       
  PSX_CIRCLE,  
  PSX_TRIANGLE,
  PSX_SQUARE,  
  PSX_L1,      
  PSX_L2,      
  PSX_L3,      
  PSX_R1,      
  PSX_R2,      
  PSX_R3,      
  PSX_UD,      
  PSX_LR,      
  PSX_START,   
  PSX_SELECT,  

  // right stick
  PSX_RUD,      
  PSX_RLR,      

  PAD_EASY_TRICK,
  PAD_GRAB,
  PAD_SPRAY,
  PAD_LSTICK_H,
  PAD_LSTICK_V,
  PAD_OLLIE,
  PAD_SLIDE,
  PAD_GRIND,
  PAD_SNAP,
  PAD_CARVE,
  PAD_SPEED_PUMP,
  PAD_HARD_LEFT,
  PAD_HARD_RIGHT,
  PAD_LOOK_BACK,
  PAD_SWITCH_CAMERA,

  NEXT_AI_CAM,
  PREV_AI_CAM,
  TOGGLE_AI_CAM_MODE,

#ifndef BUILD_BOOTABLE
  DUMP_FRAME_INFO,
#endif

#ifdef TARGET_PC
	TOGGLE_WIREFRAME,
#endif

  NUM_GAME_CONTROLS
};

#endif
