// misc files for ps2 link speedup

// With precompiled headers enabled, all text up to and including 
// the following line are ignored by the compiler (dc 01/18/02)
#include "global.h"

#include "widget_entity.cpp"
#include "widget_script.cpp"
#include "matfac.cpp"
#include "billboard.cpp"
#include "lensflare.cpp"
#include "camera.cpp"
#include "debug_render.cpp"
#include "element.cpp"
#include "geomgr.cpp"
#include "light.cpp"
#include "lightmgr.cpp"
#include "msgboard.cpp"
#include "particle.cpp"
#include "particlecleaner.cpp"
#include "pmesh.cpp"
#include "visrep.cpp"
//#include "actuator.cpp"
#include "capsule.cpp"
#include "cface.cpp"
#include "convex_box.cpp"
#include "colgeom.cpp"
#include "collide.cpp"
#include "fcs.cpp"
#include "generator.cpp"
#include "joint.cpp"
#include "mcs.cpp"
#include "portal.cpp"
#include "region.cpp"
#include "terrain.cpp"
#include "localize.cpp"
#include "camera_tool.cpp"
#include "semaphores.cpp"
#include "menusound.cpp"
#include "cheatmenu.cpp"
#include "GlobalData.cpp"
#include "unlock_manager.cpp"
//#include "nglcvt.cpp"