// misc files for ps2 link speedup

// With precompiled headers enabled, all text up to and including 
// the following line are ignored by the compiler (dc 01/18/02)
#include "global.h"
//#include "AIController.cpp"
#include "beam.cpp"
#include "controller.cpp"
//#include "crate.cpp"
#include "file_finder.cpp"
#include "game.cpp"
#include "mode_push.cpp"
#include "mode_timeattack.cpp"
#include "mode_meterattack.cpp"
#include "mode_headtohead.cpp"
#include "game_process.cpp"
#include "gamefile.cpp"
//#include "gun.cpp"
//#include "handheld_item.cpp"
#include "interface.cpp"
#include "item.cpp"
#include "marker.cpp"
#include "mic.cpp"
//#include "scanner.cpp"
#include "sky.cpp"
#include "sound_group.cpp"
//#include "thrown_item.cpp"
//#include "melee_item.cpp"
#include "trigger.cpp"
//#include "turret.cpp"
#include "wds.cpp"
#include "tool_dialogs.cpp"
//#include "vectorx.cpp"
#include "guidance_sys.cpp"
#include "attrib.cpp"
#include "proftimers.cpp"
#include "profcounters.cpp"
#include "serialin.cpp"

#include "heap.cpp"
#include "crc32.cpp"
// This must be the last file #included, because it #undef's malloc and free (dc 01/11/02)
#include "archalloc.cpp"

