//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by winmain.rc
//
#define IDI_MAIN_ICON                   101
#define IDR_MAIN_ACCEL                  113
#define IDD_ABOUT                       142
#define IDI_ICON1                       144
#define IDD_SPAWN                       146
#define IDD_TOOLS                       147
#define IDD_ALTER                       148
#define IDD_GROUP                       149
#define IDD_EXPORT                      150
#define IDD_CONSOLE                     151
#define IDD_TRANSLATE                   152
#define IDD_ROTATE                      153
#define IDD_SCANNER                     154
#define IDD_ITEM                        155
#define IDD_ENTITY                      156
#define IDD_CONTAINER                   157
#define IDD_DESTROY                     158
#define IDD_MATERIAL                    159
#define IDD_ALTER_TEMPLATE              160
#define IDD_MARKER                      161
#define IDD_TOOL_TEMPLATE               162
#define IDD_PATHS                       163
#define IDD_CHARACTER                   164
#define IDD_SCRIPT_ADD_BREAKPOINT       165
#define IDD_SCRIPT_MAIN_DEBUGGER        170
#define IDR_SCRIPT_DEBUGGER_MENU        171
#define IDD_SCRIPT_ADD_WATCH            171
#define IDD_CORE_ASSERT                 201
#define IDD_SIMPLE_ASSERT               202
#define IDD_PARTICLE                    203
#define IDD_PATHS2                      204
#define IDIGNOREALWAYS                  206
#define IDEXIT                          207
#define IDC_BUTTON1                     1008
#define IDC_SPAWN                       1008
#define IDC_EXPORT                      1008
#define IDC_REMOVE_GROUP                1008
#define IDC_RESET                       1008
#define IDC_REMOVE_ENTITY               1008
#define IDC_APPLY                       1008
#define IDC_DEL_PATH                    1008
#define IDC_RUN_TO_NEXT_THREAD          1008
#define IDC_TOGGLE_TRI                  1008
#define IDC_ENTITY_FILE                 1009
#define IDC_DELETE                      1009
#define IDC_CREATE                      1009
#define IDC_ADD_PATH                    1009
#define IDC_RUN_TO_NEXT_FRAME           1009
#define IDC_SAVE_AS                     1009
#define IDC_REMOVE_PT                   1009
#define IDC_ENTITY_ID                   1010
#define IDC_RUN_TO_NEXT_OBJECT          1010
#define IDC_SAVE_ALL                    1010
#define IDC_RUN_TO_NEXT_INSTANCE        1011
#define IDC_RADIO_HERO                  1012
#define IDC_RUN                         1012
#define IDC_RADIO_CAMERA                1013
#define IDC_RADIO_LOOKAT                1014
#define IDC_TOOLTABS                    1015
#define IDC_EXP_ENTITIES                1016
#define IDC_EXP_SCANNERS                1017
#define IDC_EXP_GROUPS                  1018
#define IDC_EXP_SPAWN                   1019
#define IDC_COMMAND                     1020
#define IDC_LOG                         1022
#define IDC_REFRESH                     1023
#define IDC_RADIO_MOUSE                 1024
#define IDC_GROUPS                      1025
#define IDC_MEMBERS                     1026
#define IDC_CHARACTERS                  1027
#define IDC_REMOVE_MEMBER               1028
#define IDC_ADD_CHARACTER               1029
#define IDC_MEMBER_REFRESH              1030
#define IDC_CHARACTER_REFRESH           1031
#define IDC_ENTITIES                    1032
#define IDC_TRANS_INC                   1033
#define IDC_ROT_INC                     1034
#define IDC_TRANS_POSX                  1035
#define IDC_TRANS_NEGX                  1036
#define IDC_TRANS_POSY                  1037
#define IDC_TRANS_NEGY                  1038
#define IDC_TRANS_POSZ                  1039
#define IDC_TRANS_NEGZ                  1040
#define IDC_ROT_POSX                    1041
#define IDC_ROT_NEGX                    1042
#define IDC_ROT_POSY                    1043
#define IDC_ROT_NEGY                    1044
#define IDC_ROT_POSZ                    1045
#define IDC_ROT_NEGZ                    1046
#define IDC_ALTERTABS                   1049
#define IDC_CONTINUOUS                  1051
#define IDC_STATIC_POS                  1052
#define IDC_RELATIVE                    1053
#define IDC_REFRESH_ENTITIES            1053
#define IDC_LOOKAT_X                    1055
#define IDC_LOOKAT_Y                    1056
#define IDC_LOOKAT_Z                    1057
#define IDC_SWEEP                       1058
#define IDC_APERTURE                    1059
#define IDC_APERTURE_VAL                1060
#define IDC_SWEEP_VAL                   1061
#define IDC_COLOR_R                     1062
#define IDC_RATE_MIN                    1062
#define IDC_COLOR_G                     1063
#define IDC_LIFE_MIN                    1063
#define IDC_COLOR_B                     1064
#define IDC_SPEED_MIN                   1064
#define IDC_SPEED                       1065
#define IDC_GROW_MIN                    1065
#define IDC_THICKNESS                   1066
#define IDC_FADE_MIN                    1066
#define IDC_MAX_LENGTH                  1067
#define IDC_SPINNER                     1068
#define IDC_COLOR_A                     1069
#define IDC_STATIC_ERROR                1071
#define IDC_STATIC_LOOKAT               1072
#define IDC_STATIC_COLOR                1073
#define IDC_STATIC_R                    1074
#define IDC_STATIC_G                    1075
#define IDC_STATIC_B                    1076
#define IDC_STATIC_A                    1077
#define IDC_STATIC_SPEED                1078
#define IDC_STATIC_THICKNESS            1079
#define IDC_STATIC_FADE                 1079
#define IDC_STATIC_MAX_LENGTH           1080
#define IDC_STATIC_APERTURE             1081
#define IDC_STATIC_SWEEP                1082
#define IDC_STATIC_INC                  1083
#define IDC_STATIC_VISREP               1083
#define IDC_STATIC_HEADER               1084
#define IDC_STATIC_COUNT                1085
#define IDC_COUNT                       1086
#define IDC_COUNT_SPIN                  1087
#define IDC_CAMERA_COLLISION            1088
#define IDC_ENTITY_COLLISION            1089
#define IDC_BEAMABLE                    1090
#define IDC_SCANABLE                    1091
#define IDC_NONSTATIC                   1092
#define IDC_ACTIVE                      1093
#define IDC_STATIONARY                  1094
#define IDC_ACTIONABLE                  1095
#define IDC_ACTION_FACING               1096
#define IDC_DOOR                        1097
#define IDC_DOOR_OPEN                   1098
#define IDC_INVISIBLE                   1099
#define IDC_WALKABLE                    1100
#define IDC_REPULSION                   1101
#define IDC_DIST_CLIP                   1102
#define IDC_STATIC_ENX                  1103
#define IDC_STATIC_FLAGS                1104
#define IDC_COSMETIC                    1105
#define IDC_STATIC_FLAVOR               1106
#define IDC_STATIC_NOTE                 1107
#define IDC_EXP_ITEMS                   1108
#define IDC_EXP_LEVEL                   1109
#define IDC_STATIC_CATEGORIES           1110
#define IDC_CONTAINERS                  1112
#define IDC_ITEM_LIST                   1113
#define IDC_ITEMS                       1114
#define IDC_EXP_CONTAINERS              1116
#define IDC_EXP_MATERIAL_GROUPS         1117
#define IDC_REVERSE                     1118
#define IDC_RESET_SCANNER               1119
#define IDC_RESET_ALL_SCANNERS          1120
#define IDC_GEN_NAME                    1121
#define IDC_GEN_SUFFIX                  1122
#define IDC_STATIC_SPAWN                1123
#define IDC_ORIENT                      1125
#define IDC_DIST                        1126
#define IDC_MOUSE_TRANS                 1127
#define IDC_MOUSE_TRANS_REL             1128
#define IDC_MOUSE_TRANS_SPEED           1129
#define IDC_MOUSE_ROT                   1130
#define IDC_MOUSE_ROT_REL               1131
#define IDC_MOUSE_ROT_SPEED             1132
#define IDC_HP                          1133
#define IDC_HP_SPIN                     1134
#define IDC_REMAIN_ACTIVE               1135
#define IDC_REMAIN_VISIBLE              1136
#define IDC_SINGLE_BLOW                 1137
#define IDC_EFFECT                      1138
#define IDC_EFFECT_STRING               1139
#define IDC_SOUND                       1140
#define IDC_SOUND_STRING                1141
#define IDC_VISREP                      1143
#define IDC_VISREP_STRING               1144
#define IDC_LIFETIME                    1145
#define IDC_INVULNERABLE                1146
#define IDC_AUTO_AIM                    1147
#define IDC_BIO                         1148
#define IDC_MECH                        1149
#define IDC_MATERIALS                   1150
#define IDC_COLOR                       1159
#define IDC_ALPHA_SPIN                  1160
#define IDC_X_WIDTH                     1161
#define IDC_STATIC_MARKER               1162
#define IDC_Z_WIDTH                     1163
#define IDC_Y_WIDTH                     1164
#define IDC_CRAWL_PINPOINT              1165
#define IDC_X_SPIN                      1166
#define IDC_Z_SPIN                      1167
#define IDC_Y_SPIN                      1168
#define IDC_STATIC_X_WIDTH              1169
#define IDC_STATIC_Z_WIDTH              1170
#define IDC_STATIC_Y_WIDTH              1171
#define IDC_RENDER                      1172
#define IDC_PATHS                       1173
#define IDC_DEL_POINT                   1177
#define IDC_CLEAR                       1178
#define IDC_EXP_PATHS                   1178
#define IDC_RADIO_NODE                  1179
#define IDC_EXP_BRAIN_INFO              1179
#define IDC_RADIO_EDGE                  1180
#define IDC_STATIC_MODE                 1181
#define IDC_AUTO_EDGE                   1182
#define IDC_RADIO_TEST                  1183
#define IDC_STATIC_PATH                 1184
#define IDC_DEL_EDGE                    1185
#define IDC_ADD_EDGE                    1186
#define IDC_WEIGHT_MOD                  1187
#define IDC_STATIC_WEIGHT_MOD           1188
#define IDC_EDGE_APPLY                  1189
#define IDC_EDGE_PATROL                 1190
#define IDC_NODE_DUCK                   1191
#define IDC_NODE_COVER                  1192
#define IDC_NODE_SEEK                   1193
#define IDC_NODE_PATROL_DELAY           1194
#define IDC_STATIC_NODE_FLAGS           1195
#define IDC_STATIC_IDLE_AI              1196
#define IDC_IDLE_AI                     1197
#define IDC_STATIC_CHARACTER            1198
#define IDC_STATIC_ALERT_AI             1199
#define IDC_ALERT_AI                    1200
#define IDC_STATIC_ACTIVE_AI            1201
#define IDC_ACTIVE_AI                   1202
#define IDC_STATIC_AI                   1203
#define IDC_EDGE_PATROL_0               1204
#define IDC_EDGE_PATROL_2               1205
#define IDC_EDGE_PATROL_3               1206
#define IDC_EDGE_PATROL_4               1207
#define IDC_EDGE_PATROL_5               1208
#define IDC_EDGE_PATROL_6               1209
#define IDC_EDGE_PATROL_7               1210
#define IDC_EDGE_PATROL_1               1211
#define IDC_STATIC_PATROL               1212
#define IDC_PERPETUATE_EDGE_PATROL      1213
#define IDC_PERPETUATE_ALL_PATROL       1214
#define IDC_INSTANCE                    1214
#define IDC_THREAD                      1215
#define IDC_OBJECT                      1216
#define IDC_OBJECT_NUM                  1217
#define IDC_INSTANCE_NUM                1218
#define IDC_TYPE                        1218
#define IDC_THREAD_NUM                  1219
#define IDC_DATA                        1219
#define IDC_BREAKPOINTS                 1220
#define IDC_DATA_TYPE                   1220
#define IDC_REMOVE_BREAKPOINT           1221
#define IDC_TOGGLE_BREAKPOINT           1222
#define IDC_IFC_ENTITY                  1222
#define IDC_WATCHES                     1223
#define IDC_IFC_NAME                    1223
#define IDC_REMOVE_WATCH                1224
#define IDC_PART_SYS                    1224
#define IDC_STATIC_PART_SYS             1225
#define IDC_STATIC_RATE                 1226
#define IDC_RATE_MAX                    1227
#define IDC_RATE                        1228
#define IDC_STATIC_VARIANCE_RATE        1229
#define IDC_RATE_VARIANCE               1230
#define IDC_STATIC_LIFE                 1231
#define IDC_LIFE                        1232
#define IDC_STATIC_VARIANCE_LIFE        1233
#define IDC_LIFE_VARIANCE               1234
#define IDC_STATIC_VARIANCE_SPEED       1235
#define IDC_SPEED_VARIANCE              1236
#define IDC_STATIC_VARIANCE_SCALE       1237
#define IDC_SCALE_VARIANCE              1238
#define IDC_LIFE_MAX                    1239
#define IDC_STATIC_GROW                 1240
#define IDC_BASESPEED                   1241
#define IDC_SPEED_MAX                   1242
#define IDC_GROW                        1243
#define IDC_GROW_MAX                    1244
#define IDC_FADE                        1245
#define IDC_FADE_MAX                    1246
#define IDC_RESET_SYS                   1247
#define IDC_RESET_ALL_SYS               1248
#define IDC_SAVE                        1249
#define IDC_EXPORT_PATH                 1250
#define IDC_LOAD_PATH                   1251
#define IDC_TEST_PATH                   1252
#define IDC_CLEAR_PATH                  1253
#define IDC_FILENAME                    2000
#define IDC_EXPRESSION                  2001
#define IDC_MESSAGE                     2002
#define IDC_LINENUMBER                  2003
#define IDDEBUG                         2004
#define IDC_CALLSTACK                   2005
#define IDM_EXIT                        40001
#define IDM_CHANGEDEVICE                40010
#define IDM_TOGGLEFULLSCREEN            40011
#define IDM_HELP                        40012
#define IDM_ADD_WATCH                   40014
#define IDM_THREAD_BREAK                40015
#define IDM_ADD_BREAKPOINT              40016
#define IDM_AUTO_UPDATES                40017
#define IDM_ENABLE_ALL_BREAKPOINTS      40018
#define IDM_DISABLE_ALL_BREAKPOINTS     40019

// Next default values for NEW objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         40020
#define _APS_NEXT_CONTROL_VALUE         1253
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
