// script_controller_signals.h

// For each signal needed at the level of class entity, add a line of the form:
//   MAC( SIGNAL, "owner::SIGNAL" )

MAC( SIGNAL_0,          "script_mfg::SIGNAL_0" )
MAC( SIGNAL_1,          "script_mfg::SIGNAL_1" )
MAC( SIGNAL_2,          "script_mfg::SIGNAL_2" )
MAC( SIGNAL_3,          "script_mfg::SIGNAL_3" )
MAC( SIGNAL_4,          "script_mfg::SIGNAL_4" )
MAC( SIGNAL_5,          "script_mfg::SIGNAL_5" )
MAC( SIGNAL_6,          "script_mfg::SIGNAL_6" )
MAC( SIGNAL_7,          "script_mfg::SIGNAL_7" )
MAC( SIGNAL_8,          "script_mfg::SIGNAL_8" )
MAC( SIGNAL_9,          "script_mfg::SIGNAL_9" )
MAC( SIGNAL_10,         "script_mfg::SIGNAL_10" )
MAC( SIGNAL_11,         "script_mfg::SIGNAL_11" )
MAC( SIGNAL_12,         "script_mfg::SIGNAL_12" )
MAC( SIGNAL_13,         "script_mfg::SIGNAL_13" )
MAC( SIGNAL_14,         "script_mfg::SIGNAL_14" )
MAC( SIGNAL_15,         "script_mfg::SIGNAL_15" )
MAC( SIGNAL_16,         "script_mfg::SIGNAL_16" )
MAC( SIGNAL_17,         "script_mfg::SIGNAL_17" )
MAC( SIGNAL_18,         "script_mfg::SIGNAL_18" )
MAC( SIGNAL_19,         "script_mfg::SIGNAL_19" )
MAC( SIGNAL_20,         "script_mfg::SIGNAL_20" )
MAC( SIGNAL_21,         "script_mfg::SIGNAL_21" )
MAC( SIGNAL_22,         "script_mfg::SIGNAL_22" )
MAC( SIGNAL_23,         "script_mfg::SIGNAL_23" )
MAC( SIGNAL_24,         "script_mfg::SIGNAL_24" )
MAC( SIGNAL_25,         "script_mfg::SIGNAL_25" )
MAC( SIGNAL_26,         "script_mfg::SIGNAL_26" )
MAC( SIGNAL_27,         "script_mfg::SIGNAL_27" )
MAC( SIGNAL_28,         "script_mfg::SIGNAL_28" )
MAC( SIGNAL_29,         "script_mfg::SIGNAL_29" )
MAC( SIGNAL_30,         "script_mfg::SIGNAL_30" )
MAC( SIGNAL_31,         "script_mfg::SIGNAL_31" )

MAC( MUSIC_TRACK_SWITCH,"script_mfg::MUSIC_TRACK_SWITCH" )
MAC( MUSIC_FINISHED,    "script_mfg::MUSIC_FINISHED" )

