/*  THIS FILE IS AUTOMATICALLY GENERATED BY EXPORT FROM THE EXCEL FILE:  BEACHDATA.XLS
    ALL CHANGES SHOULD BE MADE IN EXCEL AND RE_EXPORTED.  DO NOT HAND EDIT.
    David Cook, Treyarch, 6/25/01
*/

#ifndef BEACHDATA_H
#define BEACHDATA_H

enum {
    BEACH_ANTARCTICA,
    BEACH_BELLS,
    BEACH_CORTESBANK,
    BEACH_GLAND,
    BEACH_JAWS,
    BEACH_JEFFERSONBAY,
    BEACH_MAVERICKS,
    BEACH_MUNDAKA,
    BEACH_PIPELINE,
    BEACH_SEBASTIAN,
    BEACH_TEAHUPOO,
    BEACH_TRESTLES,
    BEACH_INDOOR,
    BEACH_COSMOS,
    BEACH_CURRENSPOINT,
    BEACH_BELLSNIGHT,
    BEACH_GLAND2,
    BEACH_JAWSBIG,
    BEACH_KIRRA,
    BEACH_KIRRA2,
    BEACH_MAVBIG,
    BEACH_MUNDAKA2,
    BEACH_TEANIGHT,
    BEACH_TEAEVE,
    BEACH_OPENSEA,
    BEACH_LAST
};

enum {
    MAP_LOC_NOWHERE,
    MAP_LOC_ANTARCTICA,
    MAP_LOC_BELLS,
    MAP_LOC_CORTESBANK,
    MAP_LOC_GLAND,
    MAP_LOC_JAWS,
    MAP_LOC_JEFFERSONBAY,
    MAP_LOC_MAVERICKS,
    MAP_LOC_MUNDAKA,
    MAP_LOC_PIPELINE,
    MAP_LOC_SEBASTIAN,
    MAP_LOC_TEAHUPOO,
    MAP_LOC_TRESTLES,
    MAP_LOC_INDOOR,
    MAP_LOC_COSMOS,
    MAP_LOC_CURRENSPOINT,
    MAP_LOC_KIRRA,
    MAP_LOC_LAST,
};

typedef struct BeachDataStruct {
    char name[32];                               // Name
    char folder[32];                             // Folder
    char stashfile[16];                          // Stash
    char fe_name[32];                            // FE Name
    char career_name[32];                        // Career Name
    char bottomname[32];                         // Bottom
    char capsulename[32];                        // Capsule
    int bdir;                                    // R/L
    float start_vx;                              // Initial Velocity      vx
    float start_vz;                              //                       vz
    float water_friction;                        // 
    float skag_friction;                         // 
    float stick_force;                           // Physics
    float gravity;                               // 
    float board_speed;                           // 
    float board_carving;                         // 
    float zoom_factor;                           //                       Used by Beach Camera for distance from surfer
    float cutoff_freq;                           // 
    float break_zoom;                            // 
    float break_mod;                             // 
    float darkscale;                             // Wave texturing        Dark Scale
    float darkoff;                               //                       Dark Offset
    float darkhiscale;                           //                       Hi angle Dark Scale
    float darkhioff;                             //                       Hi angle Dark Offset
    float darkunderscale;                        //                       Underwater Dark Scale
    float darkunderoff;                          //                       Underwater Dark Offset
    float highscale;                             //                       High Scale
    float highoff;                               //                       High Offset
    float corescale;                             //                       Core Scale
    float coreoff;                               //                       Core Offset
    float transcale;                             //                       Trans Scale
    int transmin;                                //                       Trans Min
    float sunx;                                  //                       Sun X
    float suny;                                  //                       Sun Y
    float sunz;                                  //                       Sun Z
    int foamintube;                              //                       Foam Pos 0=lip 1=tube 2=both 3=none
    float lensflarex;                            // Lensflare             Lensflare X Pos
    float lensflarey;                            //                       Lensflare Y Pos
    float lensflarez;                            //                       Lensflare Z Pos
    float level_duration;                        // time in level
    int is_small_wave;                           // whether or not big
    int is_big_wave;                             // whether or not big
    int use_wetsuit;                             // Are we using wetsuits
    int map_location;                            // location on the map
    int framelock;                               // Fixed frames per second
    int has_movie;                               // does this beach have a movie
    float bumpscale;                             // Xbox texturing        Bump Scale
    int colornear;                               //                       Near water color
    int colorfar;                                //                       Far water color
    float rgbfadescale;                          //                       RGB Falloff Scale
    float rgbfadeoffset;                         //                       RGB Falloff Offset
    float rgbfademin;                            //                       RGB Falloff Min
    float rgbfademax;                            //                       RGB Falloff Max
    float bumpfadescale;                         //                       Bump Falloff Scale
    float bumpfadeoffset;                        //                       Bump Falloff Offset
    float bumpfademin;                           //                       Bump Falloff Min
    float bumpfademax;                           //                       Bump Falloff Max
    float alphafadescale;                        //                       Alpha Falloff Scale
    float alphafadeoffset;                       //                       Alpha Falloff Offset
    float alphafademin;                          //                       Alpha Falloff Min
    float alphafademax;                          //                       Alpha Falloff Max
    int colorspecular;                           //                       Specular water color
    float specularfadescale;                     //                       Specular Falloff Scale
    float specularfadeoffset;                    //                       Specular Falloff Offset
    float sunx_xbox;                             //                       Sun X
    float suny_xbox;                             //                       Sun Y
    float sunz_xbox;                             //                       Sun Z
    float gcbumpscale;                           // GameCube texturing    Bump Scale
    int gccolornear;                             //                       Near water color
    int gccolorfar;                              //                       Far water color
    float gcrgbfadescale;                        //                       RGB Falloff Scale
    float gcrgbfadeoffset;                       //                       RGB Falloff Offset
    float gcbumpfadescale;                       //                       Bump Falloff Scale
    float gcbumpfadeoffset;                      //                       Bump Falloff Offset
    float gcalphafadescale;                      //                       Alpha Falloff Scale
    float gcalphafadeoffset;                     //                       Alpha Falloff Offset
    int gccolorspecular;                         //                       Specular water color
    float gcspecularfadescale;                   //                       Specular Falloff Scale
    float gcspecularfadeoffset;                  //                       Specular Falloff Offset
    float sunx_gc;                               //                       Sun X
    float suny_gc;                               //                       Sun Y
    float sunz_gc;                               //                       Sun Z
    int has_beach_board;                         //                       has beach board
    int underwaterambient;                       // Under water ambient light color
    float ambient_boost;                         // Boost in ambient for Xbox
    float underwater_boost;                      // Boost in ambient for Xbox
    float dir_reduction;                         // Reduction in dir light for Xbox
} BeachData, *BeachDataPtr;

extern BeachData BeachDataArray[];
void BEACHDATA_Load(void);

#endif /* #ifndef BEACHDATA_H */
