/*  THIS FILE IS AUTOMATICALLY GENERATED BY EXPORT FROM THE EXCEL FILE:  BOARDDATA.XLS
    ALL CHANGES SHOULD BE MADE IN EXCEL AND RE_EXPORTED.  DO NOT HAND EDIT.
*/

#ifndef BOARDDATA_H
#define BOARDDATA_H

#include "surferdata.h"
#include "beachdata.h"

struct BoardData {
    int balance;
    int speed;
    int air;
    int spin;
    int height_feet;
    int height_inches;
    int width;
    float thickness;
    int tail_type;
};


#define MAX_BOARDS  9 
extern BoardData SurferBoardArray[SURFER_LAST][MAX_BOARDS];
extern BoardData LocationBoardArray[MAP_LOC_LAST];
extern int NumBoards[SURFER_LAST];   // number of boards each surfer has
void BOARDDATA_Load(void);
void GetSurferBoardStats(int surfer, int board_num, int &balance, int &speed, int &air, int &spin);
void GetBeachBoardStats(int beach_num, int &balance, int &speed, int &air, int &spin);

#endif /* #ifndef BOARDDATA_H */
