MAC(BOARD_ANIM_ZERO, "BOARD_000")
MAC(BOARD_DUMMY_ANIM1, "ALL_DUMMY_ANIM1_SB")
MAC(BOARD_ANIM_AIR_JUDO, "ALL_AIR_JUDO_1B")//
MAC(BOARD_ANIM_AIR_INDY, "ALL_AIR_INDY_1B")//
MAC(BOARD_ANIM_AIR_LIEN, "ALL_AIR_LIEN_1B")//
MAC(BOARD_ANIM_AIR_MELON, "ALL_AIR_MELON_1B")//
MAC(BOARD_ANIM_AIR_MUTE_GRAB, "ALL_AIR_MUTE_GRAB_1B")//
MAC(BOARD_ANIM_AIR_NOSE_GRAB, "ALL_AIR_NOSE_GRAB_1B")//
MAC(BOARD_ANIM_AIR_NUCLEAR, "ALL_AIR_NUCLEAR_1B")//
MAC(BOARD_ANIM_AIR_SHOVETHIS, "ALL_AIR_SHOVETHIS_1B")//
MAC(BOARD_ANIM_AIR_ROCKET_GRAB, "ALL_AIR_ROCKET_GRAB_1B")//
MAC(BOARD_ANIM_AIR_STALEFISH, "ALL_AIR_STALEFISH_1B")//
MAC(BOARD_ANIM_AIR_TAIL_GRAB, "ALL_AIR_TAIL_GRAB_1B")//
MAC(BOARD_ANIM_AIR_ROASTBEEF, "ALL_AIR_ROASTBEEF_1B")//
MAC(BOARD_ANIM_ALL_AIR_HEELFLIP_1, "ALL_AIR_HEELFLIP_1B")//
MAC(BOARD_ANIM_ALL_AIR_FLIP_B_1, "ALL_AIR_FLIP_B_1B")//
MAC(BOARD_ANIM_ALL_AIR_FLIP_F_1, "ALL_AIR_FLIP_F_1B")//
MAC(BOARD_ANIM_ALL_AIR_FLIP_L_1, "ALL_AIR_FLIP_L_1_B")//
MAC(BOARD_ANIM_ALL_AIR_FLIP_R_1, "ALL_AIR_FLIP_R_1_B")//
MAC(BOARD_ANIM_ALL_AIR_KICKFLIP_1, "ALL_AIR_KICKFLIP_1B")//
MAC(BOARD_ANIM_ALL_AIR_RODEO_1, "ALL_AIR_RODEO_1B")//
MAC(BOARD_ANIM_ALL_AIR_SUNCHILD_1, "ALL_AIR_SUNCHILD_1B")//
MAC(BOARD_ANIM_AIR_HELI_720_1, "ALL_AIR_HELI_720_1B")//
MAC(BOARD_ANIM_AIR_ALLEY_OOP_1, "ALL_AIR_ALLEY_OOP_1B")//
MAC(BOARD_ANIM_AIR_HANGMAN_1, "ALL_AIR_HANGMAN_1B")//
MAC(BOARD_ANIM_AIR_MONKEYMAN, "ALL_AIR_MONKEYMAN_B")//
MAC(BOARD_ANIM_AIR_WALK_1, "ALL_AIR_WALK_1B")//
MAC(BOARD_ANIM_AIR_SUPERMAN_1, "ALL_AIR_SUPERMAN_1B")//
MAC(BOARD_ANIM_AIR_TWEAKER_1, "ALL_AIR_TWEAKER_1B")//
MAC(BOARD_ANIM_AIR_NACNAC_1, "ALL_AIR_NACNAC_1B")//
MAC(BOARD_ANIM_AIR_SHOVEIT_1, "ALL_AIR_SHOVEIT_1B")//
MAC(BOARD_ANIM_AIR_METHOD, "ALL_AIR_METHOD_1B")//
MAC(BOARD_ANIM_AIR_INDIAN_1, "ALL_AIR_INDIAN_1B")
MAC(BOARD_ANIM_AIR_CHANGMAN_1, "ALL_AIR_CHANGMAN_1B")//

//  don't change the order for exit moves
MAC(BOARD_ANIM_AIR_EXIT_1, "ALL_AIR_EXIT_1B")//
MAC(BOARD_ANIM_AIR_EXIT_11, "ALL_AIR_EXIT_11B")//
MAC(BOARD_ANIM_AIR_EXIT_2, "ALL_AIR_EXIT_2B")//
MAC(BOARD_ANIM_AIR_EXIT_21, "ALL_AIR_EXIT_21B")//
MAC(BOARD_ANIM_AIR_EXIT_3, "ALL_AIR_EXIT_3B")//
MAC(BOARD_ANIM_AIR_EXIT_31, "ALL_AIR_EXIT_31B")//
MAC(BOARD_ANIM_AIR_EXIT_4, "ALL_AIR_EXIT_4B")//
MAC(BOARD_ANIM_AIR_EXIT_41, "ALL_AIR_EXIT_41B")//
MAC(BOARD_ANIM_AIR_EXIT_5, "ALL_AIR_EXIT_5B")//
MAC(BOARD_ANIM_AIR_EXIT_51, "ALL_AIR_EXIT_51B")//
MAC(BOARD_ANIM_AIR_EXIT_6, "ALL_AIR_EXIT_6B")//
MAC(BOARD_ANIM_AIR_EXIT_61, "ALL_AIR_EXIT_61B")//
MAC(BOARD_ANIM_AIR_EXIT_7, "ALL_AIR_EXIT_7B")//
MAC(BOARD_ANIM_AIR_EXIT_71, "ALL_AIR_EXIT_71B")//
MAC(BOARD_ANIM_AIR_EXIT_8, "ALL_AIR_EXIT_8B")//
MAC(BOARD_ANIM_AIR_EXIT_81, "ALL_AIR_EXIT_81B")//
//  end exit moves

MAC(BOARD_ANIM_TRK_FACE_SHOVEIT_1, "ALL_TRK_FACE_SHOVEIT_1B")
MAC(BOARD_ANIM_TRK_FACE_DARKSLIDE_1, "ALL_TRK_FACE_DARKSLIDE_1B")
MAC(BOARD_ANIM_TRK_FACE_MANUAL_1, "ALL_TRK_FACE_MANUAL_1B")
MAC(BOARD_ANIM_TRK_FLOAT_L_1, "ALL_TRK_FLOAT_L_1B")//
MAC(BOARD_ANIM_TRK_FLOAT_R_1, "ALL_TRK_FLOAT_R_1B")//
MAC(BOARD_ANIM_TRK_INTO_FLOAT_1, "ALL_TRK_INTO_FLOAT_1B")//
MAC(BOARD_ANIM_TRN_SNAP_L_1, "ALL_TRN_SNAP_L_1B")//
MAC(BOARD_ANIM_TRN_SNAP_R_1, "ALL_TRN_SNAP_R_1B")//
MAC(BOARD_ANIM_TRK_CUTBACK_L_1, "ALL_TRK_CUTBACK_L_1B")
MAC(BOARD_ANIM_TRK_CUTBACK_R_1, "ALL_TRK_CUTBACK_R_1B")
MAC(BOARD_ANIM_TRK_CUTBACK_L_11, "ALL_TRK_CUTBACK_L_11B")
MAC(BOARD_ANIM_TRK_CUTBACK_R_11, "ALL_TRK_CUTBACK_R_11B")
MAC(BOARD_ANIM_TRK_CUTBACK_L_2, "ALL_TRK_CUTBACK_L_2B")
MAC(BOARD_ANIM_TRK_CUTBACK_R_2, "ALL_TRK_CUTBACK_R_2B")
MAC(BOARD_ANIM_TRK_CUTBACK_L_21, "ALL_TRK_CUTBACK_L_21B")
MAC(BOARD_ANIM_TRK_CUTBACK_R_21, "ALL_TRK_CUTBACK_R_21B")
MAC(BOARD_ANIM_TRK_CUTBACK_L_3, "ALL_TRK_CUTBACK_L_3B")
MAC(BOARD_ANIM_TRK_CUTBACK_R_3, "ALL_TRK_CUTBACK_R_3B")
MAC(BOARD_ANIM_TRK_CUTBACK_L_31, "ALL_TRK_CUTBACK_L_31B")
MAC(BOARD_ANIM_TRK_CUTBACK_R_31, "ALL_TRK_CUTBACK_R_31B")
MAC(BOARD_ANIM_TRK_CUTBACK_L_4, "ALL_TRK_CUTBACK_L_4B")
MAC(BOARD_ANIM_TRK_CUTBACK_R_4, "ALL_TRK_CUTBACK_R_4B")
MAC(BOARD_ANIM_TRK_CUTBACK_L_41, "ALL_TRK_CUTBACK_L_41B")
MAC(BOARD_ANIM_TRK_CUTBACK_R_41, "ALL_TRK_CUTBACK_R_41B")
MAC(BOARD_ANIM_TRK_CUTBACK_L_5, "ALL_TRK_CUTBACK_L_5B")
MAC(BOARD_ANIM_TRK_CUTBACK_R_5, "ALL_TRK_CUTBACK_R_5B")
MAC(BOARD_ANIM_TRK_CUTBACK_L_51, "ALL_TRK_CUTBACK_L_51B")
MAC(BOARD_ANIM_TRK_CUTBACK_R_51, "ALL_TRK_CUTBACK_R_51B")
MAC(BOARD_ANIM_BAS_DUCKDIVE_DOWN_1, "ALL_BAS_DUCKDIVE_DOWN_1B")//
MAC(BOARD_ANIM_BAS_DUCKDIVE_IDLE_1, "ALL_BAS_DUCKDIVE_IDLE_1B")//
MAC(BOARD_ANIM_BAS_DUCKDIVE_UP_1, "ALL_BAS_DUCKDIVE_UP_1B")//
MAC(BOARD_ANIM_CROUCH_SPD_1, "ALL_BAS_CROUCH_SPD_1B")//
MAC(BOARD_ANIM_STALL, "ALL_BAS_STALL_B")
MAC(BOARD_ANIM_SLOW_STALL, "ALL_BAS_SLOW_STALL_B")  //  Short Stall, for when too far from the tube
MAC(BOARD_ANIM_SUPER_STALL_1, "ALL_BAS_SUPER_STALL_1B")			//  out of tube super stall, 
MAC(BOARD_ANIM_TRK_TUBE_FS_SUPERSTALL_1, "ALL_TRK_TUBE_FS_SUPERSTALL_1B")			//  And in-tube super stall.
MAC(BOARD_ANIM_IDLE_LAYING, "ALL_IDLE_LAYING_1B")//
MAC(BOARD_ANIM_LIE_PADDLE, "ALL_LIE_PADDEL_1B")//
MAC(BOARD_ANIM_LIE_PADDLE_BK, "ALL_LIE_PADDEL_BK_1B")//
MAC(BOARD_ANIM_LIE_PADDEL_L_1, "ALL_LIE_PADDEL_L_1B")//
MAC(BOARD_ANIM_LIE_PADDEL_R_1, "ALL_LIE_PADDEL_R_1B")//
//MAC(BOARD_ANIM_GET_ON_BOARD_1, "ALL_TRANS_GET_ON_BOARD_1B")  //  From swimming to lying on the board.
MAC(BOARD_ANIM_GET_ON_BOARD_1, "ALL_W_GOBB")  //  From swimming to lying on the board.
MAC(BOARD_ANIM_W_1_L_GOB, "ALL_W_1_L_GOBB")
MAC(BOARD_ANIM_W_1_R_GOB, "ALL_W_1_R_GOBB")
MAC(BOARD_ANIM_TRN_INVERT_1, "ALL_TRN_INVERT_1B")
MAC(BOARD_ANIM_TAKE_OFF_WEAK_1, "ALL_TAKE_OFF_WEAK_1B")//
MAC(BOARD_ANIM_TAKE_OFF_REG_1, "ALL_TAKE_OFF_REG_1B")//
MAC(BOARD_ANIM_TAKE_OFF_LATE_1, "ALL_TAKE_OFF_LATE_1B")//
MAC(BOARD_ANIM_TAKE_OFF_LATE_FK_1, "ALL_TAKE_OFF_LATE_FK_1B")//
MAC(BOARD_ANIM_TRN_L_TAILSLIDE_1, "ALL_TRN_L_TAILSLIDE_1B")//
MAC(BOARD_ANIM_TRN_R_TAILSLIDE_1, "ALL_TRN_R_TAILSLIDE_1B")//
MAC(BOARD_ANIM_IDLE_ON_AIR, "ALL_IDLE_ON_AIR_B")//
MAC(BOARD_ANIM_BAS_FREEFALL, "ALL_BAS_FREEFALL_1_B")//
MAC(BOARD_ANIM_TRK_TUBE_QCUT_L_1, "ALL_TRK_TUBE_QCUT_L_1B")//
MAC(BOARD_ANIM_TRK_TUBE_QCUT_R_1, "ALL_TRK_TUBE_QCUT_R_1B")//
MAC(BOARD_ANIM_TRK_FACE_CRUZER_1, "ALL_TRK_FACE_CRUZER_1B")
MAC(BOARD_ANIM_TRK_AERIAL_HOP_UP, "ALL_TRK_AERIAL_HOP_UP_SB")
//  end trick with board anims
// everything above should be synched with anims in shared anim

MAC(BOARD_ANIM_WIP_MISSED_DROP, "ALL_WIP_MISSED_DROP_B")
MAC(BOARD_ANIM_W_1_AIR_B_DIS, "ALL_W_1_AIR_B_DISB")
MAC(BOARD_ANIM_W_1_AIR_B_FRF, "ALL_W_1_AIR_B_FRFB")
MAC(BOARD_ANIM_W_1_AIR_B_IMP, "ALL_W_1_AIR_B_IMPB")
MAC(BOARD_ANIM_W_1_AIR_F_DIS, "ALL_W_1_AIR_F_DISB")
MAC(BOARD_ANIM_W_1_AIR_F_FRF, "ALL_W_1_AIR_F_FRFB")
MAC(BOARD_ANIM_W_1_AIR_F_IMP, "ALL_W_1_AIR_F_IMPB")
MAC(BOARD_ANIM_W_1_AIR_R_DIS, "ALL_W_1_AIR_R_DISB")
MAC(BOARD_ANIM_W_1_AIR_R_FRF, "ALL_W_1_AIR_R_FRFB")
MAC(BOARD_ANIM_W_1_AIR_R_IMP, "ALL_W_1_AIR_R_IMPB")
MAC(BOARD_ANIM_W_1_AIR_L_DIS, "ALL_W_1_AIR_L_DISB")
MAC(BOARD_ANIM_W_1_AIR_L_FRF, "ALL_W_1_AIR_L_FRFB")
MAC(BOARD_ANIM_W_1_AIR_L_IMP, "ALL_W_1_AIR_L_IMPB")
MAC(BOARD_ANIM_W_1_AIR_U_DIS, "ALL_W_1_AIR_U_DISB")
MAC(BOARD_ANIM_W_1_AIR_U_FRF, "ALL_W_1_AIR_U_FRFB")
MAC(BOARD_ANIM_W_1_AIR_U_IMP, "ALL_W_1_AIR_U_IMPB")
MAC(BOARD_ANIM_W_1_BAL_B_DIS, "ALL_W_1_BAL_B_DISB")
MAC(BOARD_ANIM_W_1_BAL_B_FRF, "ALL_W_1_BAL_B_FRFB")
MAC(BOARD_ANIM_W_1_BAL_B_IMP, "ALL_W_1_BAL_B_IMPB")
MAC(BOARD_ANIM_W_1_TAK_R_DIS, "ALL_W_1_TAK_R_DISB")
MAC(BOARD_ANIM_W_1_TAK_R_FRF, "ALL_W_1_TAK_R_FRFB")
MAC(BOARD_ANIM_W_1_TAK_R_IMP, "ALL_W_1_TAK_R_IMPB")
MAC(BOARD_ANIM_W_1_TAK_FLAT_WOBBLE, "ALL_W_1_TAK_FLAT_WOBBLEB")
MAC(BOARD_ANIM_W_1_TAK_FLAT_DIS, "ALL_W_1_TAK_FLAT_DISB")
MAC(BOARD_ANIM_W_1_TAK_FLAT_FRF, "ALL_W_1_TAK_FLAT_FRFB")
MAC(BOARD_ANIM_W_1_TAK_FLAT_IMP, "ALL_W_1_TAK_FLAT_IMPB")
MAC(BOARD_ANIM_W_2_TRH_L_DIS, "ALL_W_2_TRH_L_DISB")
MAC(BOARD_ANIM_W_2_TRH_R_DIS, "ALL_W_2_TRH_R_DISB")
MAC(BOARD_ANIM_W_1_TAK_BACK_DIS, "ALL_W_1_TAK_BACK_DISB")
MAC(BOARD_ANIM_W_1_TAK_BACK_FRF, "ALL_W_1_TAK_BACK_FRFB")
MAC(BOARD_ANIM_W_1_TAK_BACK_IMP, "ALL_W_1_TAK_BACK_IMPB")



