/*  THIS FILE IS AUTOMATICALLY GENERATED BY EXPORT FROM THE EXCEL FILE:  BOARDDATA.XLS
    ALL CHANGES SHOULD BE MADE IN EXCEL AND RE_EXPORTED.  DO NOT HAND EDIT.
*/

#include "boarddata.h"

BoardData SurferBoardArray[SURFER_LAST][MAX_BOARDS];
BoardData LocationBoardArray[MAP_LOC_LAST];
int NumBoards[SURFER_LAST];   // number of boards each surfer has

void setBoardData(BoardData* bd, int balance, int speed, int air, int spin, int height_feet, int height_inches, int width, float thickness, int tail_type)
{
    bd->balance = balance;
    bd->speed = speed;
    bd->air = air;
    bd->spin = spin;
    bd->height_feet = height_feet;
    bd->height_inches = height_inches;
    bd->width = width;
    bd->thickness = thickness;
    bd->tail_type = tail_type;
}

void BOARDDATA_Load(void)
{
    for(int i=0; i<SURFER_LAST; i++)
         NumBoards[i] = 0;

    // Surfer Boards
    setBoardData(&SurferBoardArray[SURFER_KELLY_SLATER][ 0 ],  3 ,  4 ,  3 ,  3 ,  5 ,  10 ,  19 , 2.25f,  1 );
    setBoardData(&SurferBoardArray[SURFER_KELLY_SLATER][ 1 ],  4 ,  5 ,  3 ,  4 ,  6 ,  0 ,  17 , 2.0f,  3 );
    setBoardData(&SurferBoardArray[SURFER_KELLY_SLATER][ 2 ],  4 ,  5 ,  4 ,  4 ,  6 ,  1 ,  18 , 2.15f,  1 );
    setBoardData(&SurferBoardArray[SURFER_KELLY_SLATER][ 3 ],  5 ,  6 ,  4 ,  5 ,  6 ,  3 ,  18 , 2.25f,  3 );
    setBoardData(&SurferBoardArray[SURFER_KELLY_SLATER][ 4 ],  5 ,  7 ,  5 ,  5 ,  6 ,  5 ,  18 , 2.3f,  0 );
    setBoardData(&SurferBoardArray[SURFER_KELLY_SLATER][ 5 ],  6 ,  7 ,  5 ,  6 ,  6 ,  6 ,  18 , 2.25f,  3 );
    setBoardData(&SurferBoardArray[SURFER_KELLY_SLATER][ 6 ],  7 ,  8 ,  6 ,  6 ,  6 ,  8 ,  18 , 2.25f,  0 );
    setBoardData(&SurferBoardArray[SURFER_KELLY_SLATER][ 7 ],  8 ,  9 ,  7 ,  7 ,  6 ,  10 ,  18 , 2.35f,  3 );
    setBoardData(&SurferBoardArray[SURFER_KELLY_SLATER][ 8 ],  10 ,  10 ,  8 ,  8 ,  7 ,  2 ,  18 , 2.5f,  2 );
    NumBoards[SURFER_KELLY_SLATER] = 9 ;
    setBoardData(&SurferBoardArray[SURFER_ROB_MACHADO][ 0 ],  3 ,  3 ,  4 ,  2 ,  5 ,  6 ,  19 , 2.2f,  1 );
    setBoardData(&SurferBoardArray[SURFER_ROB_MACHADO][ 1 ],  4 ,  3 ,  4 ,  2 ,  5 ,  9 ,  17 , 2.5f,  3 );
    setBoardData(&SurferBoardArray[SURFER_ROB_MACHADO][ 2 ],  4 ,  4 ,  5 ,  3 ,  5 ,  11 ,  15 , 2.7f,  1 );
    setBoardData(&SurferBoardArray[SURFER_ROB_MACHADO][ 3 ],  5 ,  5 ,  5 ,  4 ,  6 ,  1 ,  18 , 2.0f,  3 );
    setBoardData(&SurferBoardArray[SURFER_ROB_MACHADO][ 4 ],  6 ,  6 ,  6 ,  5 ,  6 ,  4 ,  16 , 2.3f,  0 );
    setBoardData(&SurferBoardArray[SURFER_ROB_MACHADO][ 5 ],  6 ,  7 ,  7 ,  5 ,  6 ,  4 ,  17 , 2.3f,  3 );
    setBoardData(&SurferBoardArray[SURFER_ROB_MACHADO][ 6 ],  7 ,  7 ,  7 ,  6 ,  6 ,  8 ,  20 , 2.6f,  0 );
    setBoardData(&SurferBoardArray[SURFER_ROB_MACHADO][ 7 ],  7 ,  8 ,  8 ,  7 ,  6 ,  8 ,  18 , 2.4f,  3 );
    setBoardData(&SurferBoardArray[SURFER_ROB_MACHADO][ 8 ],  10 ,  9 ,  10 ,  7 ,  7 ,  2 ,  19 , 2.8f,  2 );
    NumBoards[SURFER_ROB_MACHADO] = 9 ;
    setBoardData(&SurferBoardArray[SURFER_KALANI_ROBB][ 0 ],  3 ,  3 ,  3 ,  2 ,  5 ,  6 ,  19 , 2.2f,  1 );
    setBoardData(&SurferBoardArray[SURFER_KALANI_ROBB][ 1 ],  4 ,  4 ,  3 ,  3 ,  5 ,  9 ,  17 , 2.5f,  3 );
    setBoardData(&SurferBoardArray[SURFER_KALANI_ROBB][ 2 ],  5 ,  4 ,  3 ,  4 ,  5 ,  11 ,  15 , 2.7f,  1 );
    setBoardData(&SurferBoardArray[SURFER_KALANI_ROBB][ 3 ],  5 ,  5 ,  4 ,  4 ,  6 ,  1 ,  18 , 2.0f,  3 );
    setBoardData(&SurferBoardArray[SURFER_KALANI_ROBB][ 4 ],  6 ,  6 ,  5 ,  5 ,  6 ,  4 ,  16 , 2.3f,  0 );
    setBoardData(&SurferBoardArray[SURFER_KALANI_ROBB][ 5 ],  7 ,  6 ,  5 ,  6 ,  6 ,  4 ,  17 , 2.3f,  3 );
    setBoardData(&SurferBoardArray[SURFER_KALANI_ROBB][ 6 ],  8 ,  7 ,  6 ,  7 ,  6 ,  8 ,  20 , 2.6f,  0 );
    setBoardData(&SurferBoardArray[SURFER_KALANI_ROBB][ 7 ],  8 ,  8 ,  7 ,  8 ,  6 ,  8 ,  18 , 2.4f,  3 );
    setBoardData(&SurferBoardArray[SURFER_KALANI_ROBB][ 8 ],  10 ,  10 ,  8 ,  8 ,  7 ,  2 ,  19 , 2.8f,  2 );
    NumBoards[SURFER_KALANI_ROBB] = 9 ;
    setBoardData(&SurferBoardArray[SURFER_LISA_ANDERSEN][ 0 ],  4 ,  2 ,  3 ,  3 ,  5 ,  6 ,  19 , 2.2f,  1 );
    setBoardData(&SurferBoardArray[SURFER_LISA_ANDERSEN][ 1 ],  4 ,  3 ,  3 ,  4 ,  5 ,  9 ,  17 , 2.5f,  3 );
    setBoardData(&SurferBoardArray[SURFER_LISA_ANDERSEN][ 2 ],  5 ,  4 ,  4 ,  4 ,  5 ,  11 ,  15 , 2.7f,  1 );
    setBoardData(&SurferBoardArray[SURFER_LISA_ANDERSEN][ 3 ],  5 ,  5 ,  4 ,  5 ,  6 ,  1 ,  18 , 2.0f,  3 );
    setBoardData(&SurferBoardArray[SURFER_LISA_ANDERSEN][ 4 ],  6 ,  6 ,  5 ,  5 ,  6 ,  4 ,  16 , 2.3f,  0 );
    setBoardData(&SurferBoardArray[SURFER_LISA_ANDERSEN][ 5 ],  7 ,  6 ,  5 ,  6 ,  6 ,  4 ,  17 , 2.3f,  3 );
    setBoardData(&SurferBoardArray[SURFER_LISA_ANDERSEN][ 6 ],  8 ,  7 ,  6 ,  6 ,  6 ,  8 ,  20 , 2.6f,  0 );
    setBoardData(&SurferBoardArray[SURFER_LISA_ANDERSEN][ 7 ],  9 ,  8 ,  7 ,  7 ,  6 ,  8 ,  18 , 2.4f,  3 );
    setBoardData(&SurferBoardArray[SURFER_LISA_ANDERSEN][ 8 ],  10 ,  10 ,  9 ,  7 ,  7 ,  2 ,  19 , 2.8f,  2 );
    NumBoards[SURFER_LISA_ANDERSEN] = 9 ;
    setBoardData(&SurferBoardArray[SURFER_NATHAN_FLETCHER][ 0 ],  2 ,  3 ,  4 ,  4 ,  5 ,  6 ,  19 , 2.2f,  1 );
    setBoardData(&SurferBoardArray[SURFER_NATHAN_FLETCHER][ 1 ],  3 ,  4 ,  4 ,  4 ,  5 ,  9 ,  17 , 2.5f,  3 );
    setBoardData(&SurferBoardArray[SURFER_NATHAN_FLETCHER][ 2 ],  3 ,  4 ,  5 ,  5 ,  5 ,  11 ,  15 , 2.7f,  1 );
    setBoardData(&SurferBoardArray[SURFER_NATHAN_FLETCHER][ 3 ],  3 ,  5 ,  5 ,  5 ,  6 ,  1 ,  18 , 2.0f,  3 );
    setBoardData(&SurferBoardArray[SURFER_NATHAN_FLETCHER][ 4 ],  4 ,  5 ,  6 ,  5 ,  6 ,  4 ,  16 , 2.3f,  0 );
    setBoardData(&SurferBoardArray[SURFER_NATHAN_FLETCHER][ 5 ],  5 ,  6 ,  6 ,  6 ,  6 ,  4 ,  17 , 2.3f,  3 );
    setBoardData(&SurferBoardArray[SURFER_NATHAN_FLETCHER][ 6 ],  6 ,  6 ,  7 ,  7 ,  6 ,  8 ,  20 , 2.6f,  0 );
    setBoardData(&SurferBoardArray[SURFER_NATHAN_FLETCHER][ 7 ],  7 ,  8 ,  8 ,  8 ,  6 ,  8 ,  18 , 2.4f,  3 );
    setBoardData(&SurferBoardArray[SURFER_NATHAN_FLETCHER][ 8 ],  9 ,  9 ,  10 ,  8 ,  7 ,  2 ,  19 , 2.8f,  2 );
    NumBoards[SURFER_NATHAN_FLETCHER] = 9 ;
    setBoardData(&SurferBoardArray[SURFER_TOM_CARROL][ 0 ],  3 ,  4 ,  3 ,  2 ,  5 ,  6 ,  19 , 2.2f,  1 );
    setBoardData(&SurferBoardArray[SURFER_TOM_CARROL][ 1 ],  4 ,  5 ,  3 ,  3 ,  5 ,  9 ,  17 , 2.5f,  3 );
    setBoardData(&SurferBoardArray[SURFER_TOM_CARROL][ 2 ],  4 ,  5 ,  4 ,  4 ,  5 ,  11 ,  15 , 2.7f,  1 );
    setBoardData(&SurferBoardArray[SURFER_TOM_CARROL][ 3 ],  5 ,  6 ,  4 ,  4 ,  6 ,  1 ,  18 , 2.0f,  3 );
    setBoardData(&SurferBoardArray[SURFER_TOM_CARROL][ 4 ],  5 ,  7 ,  5 ,  5 ,  6 ,  4 ,  16 , 2.3f,  0 );
    setBoardData(&SurferBoardArray[SURFER_TOM_CARROL][ 5 ],  6 ,  7 ,  5 ,  5 ,  6 ,  4 ,  17 , 2.3f,  3 );
    setBoardData(&SurferBoardArray[SURFER_TOM_CARROL][ 6 ],  7 ,  8 ,  6 ,  6 ,  6 ,  8 ,  20 , 2.6f,  0 );
    setBoardData(&SurferBoardArray[SURFER_TOM_CARROL][ 7 ],  8 ,  9 ,  7 ,  7 ,  6 ,  8 ,  18 , 2.4f,  3 );
    setBoardData(&SurferBoardArray[SURFER_TOM_CARROL][ 8 ],  10 ,  10 ,  8 ,  8 ,  7 ,  2 ,  19 , 2.8f,  2 );
    NumBoards[SURFER_TOM_CARROL] = 9 ;
    setBoardData(&SurferBoardArray[SURFER_TOM_CURREN][ 0 ],  2 ,  4 ,  3 ,  2 ,  5 ,  6 ,  19 , 2.2f,  1 );
    setBoardData(&SurferBoardArray[SURFER_TOM_CURREN][ 1 ],  3 ,  5 ,  3 ,  3 ,  5 ,  9 ,  17 , 2.5f,  3 );
    setBoardData(&SurferBoardArray[SURFER_TOM_CURREN][ 2 ],  3 ,  5 ,  4 ,  3 ,  5 ,  11 ,  15 , 2.7f,  1 );
    setBoardData(&SurferBoardArray[SURFER_TOM_CURREN][ 3 ],  6 ,  6 ,  4 ,  3 ,  6 ,  1 ,  18 , 2.0f,  3 );
    setBoardData(&SurferBoardArray[SURFER_TOM_CURREN][ 4 ],  6 ,  7 ,  5 ,  4 ,  6 ,  4 ,  16 , 2.3f,  0 );
    setBoardData(&SurferBoardArray[SURFER_TOM_CURREN][ 5 ],  7 ,  7 ,  5 ,  4 ,  6 ,  4 ,  17 , 2.3f,  3 );
    setBoardData(&SurferBoardArray[SURFER_TOM_CURREN][ 6 ],  8 ,  8 ,  6 ,  5 ,  6 ,  8 ,  20 , 2.6f,  0 );
    setBoardData(&SurferBoardArray[SURFER_TOM_CURREN][ 7 ],  9 ,  9 ,  7 ,  6 ,  6 ,  8 ,  18 , 2.4f,  3 );
    setBoardData(&SurferBoardArray[SURFER_TOM_CURREN][ 8 ],  10 ,  10 ,  8 ,  8 ,  7 ,  2 ,  19 , 2.8f,  2 );
    NumBoards[SURFER_TOM_CURREN] = 9 ;
    setBoardData(&SurferBoardArray[SURFER_DONAVON_FRANKENREITER][ 0 ],  4 ,  3 ,  2 ,  3 ,  5 ,  6 ,  19 , 2.2f,  1 );
    setBoardData(&SurferBoardArray[SURFER_DONAVON_FRANKENREITER][ 1 ],  4 ,  4 ,  3 ,  4 ,  5 ,  9 ,  17 , 2.5f,  3 );
    setBoardData(&SurferBoardArray[SURFER_DONAVON_FRANKENREITER][ 2 ],  5 ,  4 ,  4 ,  4 ,  5 ,  11 ,  15 , 2.7f,  1 );
    setBoardData(&SurferBoardArray[SURFER_DONAVON_FRANKENREITER][ 3 ],  5 ,  4 ,  5 ,  5 ,  6 ,  1 ,  18 , 2.0f,  3 );
    setBoardData(&SurferBoardArray[SURFER_DONAVON_FRANKENREITER][ 4 ],  6 ,  6 ,  5 ,  5 ,  6 ,  4 ,  16 , 2.3f,  0 );
    setBoardData(&SurferBoardArray[SURFER_DONAVON_FRANKENREITER][ 5 ],  7 ,  7 ,  5 ,  5 ,  6 ,  4 ,  17 , 2.3f,  3 );
    setBoardData(&SurferBoardArray[SURFER_DONAVON_FRANKENREITER][ 6 ],  8 ,  7 ,  6 ,  6 ,  6 ,  8 ,  20 , 2.6f,  0 );
    setBoardData(&SurferBoardArray[SURFER_DONAVON_FRANKENREITER][ 7 ],  8 ,  8 ,  8 ,  7 ,  6 ,  8 ,  18 , 2.4f,  3 );
    setBoardData(&SurferBoardArray[SURFER_DONAVON_FRANKENREITER][ 8 ],  9 ,  9 ,  10 ,  8 ,  7 ,  2 ,  19 , 2.8f,  2 );
    NumBoards[SURFER_DONAVON_FRANKENREITER] = 9 ;
    setBoardData(&SurferBoardArray[SURFER_BRUCE_IRONS][ 0 ],  3 ,  3 ,  3 ,  2 ,  5 ,  6 ,  19 , 2.2f,  1 );
    setBoardData(&SurferBoardArray[SURFER_BRUCE_IRONS][ 1 ],  4 ,  4 ,  3 ,  3 ,  5 ,  9 ,  17 , 2.5f,  3 );
    setBoardData(&SurferBoardArray[SURFER_BRUCE_IRONS][ 2 ],  4 ,  5 ,  4 ,  3 ,  5 ,  11 ,  15 , 2.7f,  1 );
    setBoardData(&SurferBoardArray[SURFER_BRUCE_IRONS][ 3 ],  5 ,  6 ,  5 ,  4 ,  6 ,  1 ,  18 , 2.0f,  3 );
    setBoardData(&SurferBoardArray[SURFER_BRUCE_IRONS][ 4 ],  6 ,  7 ,  5 ,  4 ,  6 ,  4 ,  16 , 2.3f,  0 );
    setBoardData(&SurferBoardArray[SURFER_BRUCE_IRONS][ 5 ],  6 ,  7 ,  6 ,  5 ,  6 ,  4 ,  17 , 2.3f,  3 );
    setBoardData(&SurferBoardArray[SURFER_BRUCE_IRONS][ 6 ],  8 ,  8 ,  7 ,  6 ,  6 ,  8 ,  20 , 2.6f,  0 );
    setBoardData(&SurferBoardArray[SURFER_BRUCE_IRONS][ 7 ],  8 ,  9 ,  8 ,  7 ,  6 ,  8 ,  18 , 2.4f,  3 );
    setBoardData(&SurferBoardArray[SURFER_BRUCE_IRONS][ 8 ],  8 ,  8 ,  10 ,  10 ,  7 ,  2 ,  19 , 2.8f,  2 );
    NumBoards[SURFER_BRUCE_IRONS] = 9 ;
    setBoardData(&SurferBoardArray[SURFER_TRAVIS_PASTRANA][ 0 ],  9 ,  9 ,  9 ,  9 ,  5 ,  6 ,  19 , 2.2f,  1 );
    NumBoards[SURFER_TRAVIS_PASTRANA] = 1 ;
    setBoardData(&SurferBoardArray[SURFER_TONY_HAWK][ 0 ],  9 ,  9 ,  9 ,  9 ,  5 ,  6 ,  19 , 2.2f,  3 );
    NumBoards[SURFER_TONY_HAWK] = 1 ;
    setBoardData(&SurferBoardArray[SURFER_SURFREAK][ 0 ],  9 ,  9 ,  9 ,  9 ,  5 ,  6 ,  19 , 2.2f,  2 );
    NumBoards[SURFER_SURFREAK] = 1 ;
    setBoardData(&SurferBoardArray[SURFER_TIKI_GOD][ 0 ],  9 ,  9 ,  9 ,  9 ,  5 ,  6 ,  19 , 2.2f,  0 );
    NumBoards[SURFER_TIKI_GOD] = 1 ;

    // Beach Boards
    setBoardData(&LocationBoardArray[BeachDataArray[BEACH_ANTARCTICA].map_location],  10 ,  10 ,  10 ,  10 ,  5 ,  6 ,  19 , 2.2f,  2 );
    setBoardData(&LocationBoardArray[BeachDataArray[BEACH_BELLS].map_location],  10 ,  7 ,  8 ,  9 ,  5 ,  6 ,  19 , 2.2f,  1 );
    setBoardData(&LocationBoardArray[BeachDataArray[BEACH_CORTESBANK].map_location],  10 ,  8 ,  9 ,  7 ,  5 ,  6 ,  19 , 2.2f,  3 );
    setBoardData(&LocationBoardArray[BeachDataArray[BEACH_GLAND].map_location],  10 ,  9 ,  8 ,  7 ,  5 ,  6 ,  19 , 2.2f,  2 );
    setBoardData(&LocationBoardArray[BeachDataArray[BEACH_JAWS].map_location],  10 ,  7 ,  8 ,  9 ,  5 ,  6 ,  19 , 2.2f,  1 );
    setBoardData(&LocationBoardArray[BeachDataArray[BEACH_JEFFERSONBAY].map_location],  9 ,  10 ,  7 ,  8 ,  5 ,  6 ,  19 , 2.2f,  0 );
    setBoardData(&LocationBoardArray[BeachDataArray[BEACH_MAVERICKS].map_location],  7 ,  10 ,  8 ,  9 ,  5 ,  6 ,  19 , 2.2f,  3 );
    setBoardData(&LocationBoardArray[BeachDataArray[BEACH_MUNDAKA].map_location],  7 ,  10 ,  9 ,  8 ,  5 ,  6 ,  19 , 2.2f,  2 );
    setBoardData(&LocationBoardArray[BeachDataArray[BEACH_PIPELINE].map_location],  9 ,  10 ,  7 ,  8 ,  5 ,  6 ,  19 , 2.2f,  0 );
    setBoardData(&LocationBoardArray[BeachDataArray[BEACH_SEBASTIAN].map_location],  7 ,  8 ,  10 ,  9 ,  5 ,  6 ,  19 , 2.2f,  1 );
    setBoardData(&LocationBoardArray[BeachDataArray[BEACH_TEAHUPOO].map_location],  8 ,  9 ,  10 ,  7 ,  5 ,  6 ,  19 , 2.2f,  3 );
    setBoardData(&LocationBoardArray[BeachDataArray[BEACH_TRESTLES].map_location],  9 ,  8 ,  10 ,  7 ,  5 ,  6 ,  19 , 2.2f,  0 );
    setBoardData(&LocationBoardArray[BeachDataArray[BEACH_COSMOS].map_location],  7 ,  8 ,  10 ,  9 ,  5 ,  6 ,  19 , 2.2f,  2 );
    setBoardData(&LocationBoardArray[BeachDataArray[BEACH_CURRENSPOINT].map_location],  7 ,  8 ,  9 ,  10 ,  5 ,  6 ,  19 , 2.2f,  1 );
    setBoardData(&LocationBoardArray[BeachDataArray[BEACH_KIRRA].map_location],  8 ,  9 ,  7 ,  10 ,  5 ,  6 ,  19 , 2.2f,  3 );
}

void GetSurferBoardStats(int surfer, int board_num, int &balance, int &speed, int &air, int &spin)
{
    balance = SurferBoardArray[surfer][board_num].balance;
    speed = SurferBoardArray[surfer][board_num].speed;
    air = SurferBoardArray[surfer][board_num].air;
    spin = SurferBoardArray[surfer][board_num].spin;
}

void GetBeachBoardStats(int beach_num, int &balance, int &speed, int &air, int &spin)
{
    balance = LocationBoardArray[BeachDataArray[beach_num].map_location].balance;
    speed = LocationBoardArray[BeachDataArray[beach_num].map_location].speed;
    air = LocationBoardArray[BeachDataArray[beach_num].map_location].air;
    spin = LocationBoardArray[BeachDataArray[beach_num].map_location].spin;
}

