/*  THIS FILE IS AUTOMATICALLY GENERATED BY EXPORT FROM THE EXCEL FILE:  CAREERDATA.XLS
    ALL CHANGES SHOULD BE MADE IN EXCEL AND RE_EXPORTED.  DO NOT HAND EDIT.
    David Cook, Treyarch, 6/25/01
*/

#include "global.h"
#include "kshooks.h"
#include "cheat.h"
#include "careerdata.h"

CareerData CareerDataArray[32] =
{
    // Indoor
    {
         BEACH_INDOOR,
         {  0 ,  0 ,  0 ,  0 ,  0 , },
         {  0 ,  0 ,  0 ,  0 ,  0 , },
    },
    // Indoor 2
    {
         BEACH_INDOOR,
         {  0 ,  0 ,  0 ,  0 ,  0 , },
         {  0 ,  0 ,  0 ,  0 ,  0 , },
    },
    // Indoor 3
    {
         BEACH_INDOOR,
         {  0 ,  0 ,  0 ,  0 ,  0 , },
         {  0 ,  0 ,  0 ,  0 ,  0 , },
    },
    // Sebastian
    {
         BEACH_SEBASTIAN,
         {  2000 ,  10 ,  12500 ,  25000 ,  1 , },
         {  0 ,  0 ,  0 , CHEAT_TRIPPY,  5000 , },
    },
    // Trestles
    {
         BEACH_TRESTLES,
         {  10000 ,  10 ,  12500 ,  25000 ,  3 , },
         {  2 ,  0 ,  0 ,  0 ,  0 , },
    },
    // Trestles 2
    {
         BEACH_TRESTLES,
         {  10 ,  15 ,  25000 ,  50000 ,  0 , },
         {  0 ,  0 ,  0 , CHEAT_FPS_CAM,  0 , },
    },
    // Mavericks Cloudy
    {
         BEACH_MAVERICKS,
         {  70 ,  15 ,  2 ,  10000 ,  0 , },
         {  0 ,  0 ,  1 ,  1 ,  0 , },
    },
    // Mavericks Ominous
    {
         BEACH_MAVERICKS,
         {  0 ,  15 ,  25000 ,  50000 ,  0 , },
         {  0 ,  0 ,  0 ,  0 ,  0 , },
    },
    // Sebastian 2
    {
         BEACH_SEBASTIAN,
         {  10 ,  15 ,  25000 ,  50000 ,  3 , },
         {  0 ,  0 ,  0 ,  0 ,  0 , },
    },
    // Antarctica
    {
         BEACH_ANTARCTICA,
         {  15 ,  20 ,  60 ,  3 ,  0 , },
         {  3 ,  0 ,  7 ,  0 ,  0 , },
    },
    // Antarctica 2
    {
         BEACH_ANTARCTICA,
         {  6000 ,  20 ,  4 ,  0 ,  0 , },
         {  0 ,  0 ,  1 ,  0 ,  0 , },
    },
    // Jaws
    {
         BEACH_JAWS,
         {  30000 ,  20 ,  40000 ,  80000 ,  0 , },
         {  2 ,  0 ,  0 ,  0 ,  0 , },
    },
    // Pipeline
    {
         BEACH_PIPELINE,
         {  80 ,  25 ,  25000 ,  25000 ,  0 , },
         {  0 ,  0 ,  1 ,  1 ,  0 , },
    },
    // Jaws Cloudy
    {
         BEACH_JAWS,
         {  7500 ,  25 ,  100000 ,  200000 ,  0 , },
         {  0 ,  0 ,  0 , CHEAT_INCREASE_BALANCE,  0 , },
    },
    // Teahupoo
    {
         BEACH_TEAHUPOO,
         {  70000 ,  25 ,  75000 ,  150000 ,  3 , },
         {  2 ,  0 ,  0 ,  0 ,  0 , },
    },
    // Pipeline 2
    {
         BEACH_PIPELINE,
         {  17 ,  25 ,  75000 ,  150000 ,  3 , },
         {  0 ,  0 ,  0 ,  0 ,  0 , },
    },
    // Teahupoo Evening
    {
         BEACH_TEAEVE,
         {  1 ,  25 ,  50000 ,  100000 ,  0 , },
         {  0 ,  0 ,  0 ,  0 ,  0 , },
    },
    // Bells
    {
         BEACH_BELLS,
         {  18 ,  25 ,  50000 ,  100000 ,  3 , },
         {  0 ,  0 ,  0 ,  0 ,  0 , },
    },
    // Bells Night
    {
         BEACH_BELLSNIGHT,
         {  80000 ,  25 ,  100000 ,  200000 ,  0 , },
         {  2 ,  0 ,  0 , SURFER_TRAVIS_PASTRANA,  0 , },
    },
    // Currens Point
    {
         BEACH_CURRENSPOINT,
         {  20 ,  30 ,  90 ,  3 ,  0 , },
         {  0 ,  0 ,  0 ,  0 ,  0 , },
    },
    // Kirra
    {
         BEACH_KIRRA,
         {  15000 ,  30 ,  150000 ,  300000 ,  0 , },
         {  0 ,  0 ,  0 ,  0 ,  0 , },
    },
    // Kirra Evening
    {
         BEACH_KIRRA2,
         {  22 ,  35 ,  150000 ,  300000 ,  0 , },
         {  0 ,  0 ,  0 , SURFER_TONY_HAWK,  0 , },
    },
    // G-Land
    {
         BEACH_GLAND,
         {  90 ,  35 ,  50000 ,  50000 ,  0 , },
         {  0 ,  0 ,  1 ,  1 ,  0 , },
    },
    // G-Land Cloudy
    {
         BEACH_GLAND2,
         {  100000 ,  35 ,  150000 ,  300000 ,  0 , },
         {  2 ,  0 ,  0 , SURFER_SURFREAK,  0 , },
    },
    // Currens Point 2
    {
         BEACH_CURRENSPOINT,
         {  110000 ,  35 ,  0 ,  0 ,  0 , },
         {  2 ,  0 ,  0 ,  0 ,  0 , },
    },
    // Jefferson Bay
    {
         BEACH_JEFFERSONBAY,
         {  12500 ,  35 ,  200000 ,  400000 ,  75000 , },
         {  0 ,  0 ,  0 ,  0 ,  1 , },
    },
    // Mundaka
    {
         BEACH_MUNDAKA,
         {  10000 ,  35 ,  200000 ,  400000 ,  0 , },
         {  0 ,  0 ,  0 ,  0 ,  0 , },
    },
    // Jefferson Bay Rain
    {
         BEACH_JEFFERSONBAY,
         {  120000 ,  35 ,  200000 ,  400000 ,  3 , },
         {  2 ,  0 ,  0 , CHEAT_INCREASE_JUMP,  5 , },
    },
    // Mundaka Cloudy
    {
         BEACH_MUNDAKA2,
         {  25 ,  35 ,  250000 ,  500000 ,  3 , },
         {  0 ,  0 ,  0 , CHEAT_UNLOCK_ALL_SKILL_POINTS,  5 , },
    },
    // Cortes Bank
    {
         BEACH_CORTESBANK,
         {  200000 ,  40 ,  120 ,  3 ,  0 , },
         {  2 ,  0 ,  0 ,  0 ,  0 , },
    },
    // Teahupoo Night
    {
         BEACH_TEANIGHT,
         {  30 ,  40 ,  0 ,  0 ,  0 , },
         { SURFER_TIKI_GOD,  0 ,  0 ,  0 ,  0 , },
    },
    // Cosmos
    {
         BEACH_COSMOS,
         {  180 ,  0 ,  0 ,  0 ,  0 , },
         {  0 ,  0 ,  0 ,  0 ,  0 , },
    },
};
void CAREERDATA_Load(void)
{
    nglFileBuf F;
    KSReadFile("careerdata.dat", &F, 1);
    char *s = (char *) F.Buf;
    const char *format = "%[^,], %[^,], %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %f, %[^,], %d, %[^,], ";
    for (int i = 0; i < 32; ++i)
    {
         int n = sscanf(s, format,
              &CareerDataArray[i].beach_file,
              &CareerDataArray[i].name,
              &CareerDataArray[i].goal[ 0 ],
              &CareerDataArray[i].goal[ 1 ],
              &CareerDataArray[i].goal[ 2 ],
              &CareerDataArray[i].goal[ 3 ],
              &CareerDataArray[i].goal[ 4 ],
              &CareerDataArray[i].goal_param_2[ 0 ],
              &CareerDataArray[i].goal_param_2[ 1 ],
              &CareerDataArray[i].goal_param_2[ 2 ],
              &CareerDataArray[i].goal_param_2[ 3 ],
              &CareerDataArray[i].goal_param_2[ 4 ],
              &CareerDataArray[i].reward[ 0 ],
              &CareerDataArray[i].reward[ 1 ],
              &CareerDataArray[i].reward[ 2 ],
              &CareerDataArray[i].reward[ 3 ],
              &CareerDataArray[i].reward[ 4 ],
              &CareerDataArray[i].prev_levels[ 0 ],
              &CareerDataArray[i].prev_levels[ 1 ],
              &CareerDataArray[i].prev_levels[ 2 ],
              &CareerDataArray[i].prev_levels[ 3 ],
              &CareerDataArray[i].next_levels[ 0 ],
              &CareerDataArray[i].next_levels[ 1 ],
              &CareerDataArray[i].level_duration,
              &CareerDataArray[i].stash_name,
              &CareerDataArray[i].use_ai_surfer,
              &CareerDataArray[i].challenge_name
         );
         assert(27 == n);
         verify((s = strchr(s, '\n')) != NULL);
         ++s;
    }
    KSReleaseFile(&F);
}
stringx LevelNameArray[LEVEL_LAST] = {
    "LEVEL_INDOOR_1",
    "LEVEL_INDOOR_2",
    "LEVEL_INDOOR_3",
    "LEVEL_SEBASTIAN_1",
    "LEVEL_TRESTLES_1",
    "LEVEL_TRESTLES_2",
    "LEVEL_MAVERICKS_CLOUDY",
    "LEVEL_MAVERICKS_OMINOUS",
    "LEVEL_SEBASTIAN_2",
    "LEVEL_ANTARCTICA_1",
    "LEVEL_ANTARCTICA_2",
    "LEVEL_JAWS",
    "LEVEL_PIPELINE_1",
    "LEVEL_JAWS_CLOUDY",
    "LEVEL_TEAHUPOO",
    "LEVEL_PIPELINE_2",
    "LEVEL_TEAHUPOO_EVENING",
    "LEVEL_BELLS",
    "LEVEL_BELLS_NIGHT",
    "LEVEL_CURRENSPOINT_1",
    "LEVEL_KIRRA",
    "LEVEL_KIRRA_EVENING",
    "LEVEL_GLAND",
    "LEVEL_GLAND_CLOUDY",
    "LEVEL_CURRENSPOINT_2",
    "LEVEL_JEFFERSONBAY",
    "LEVEL_MUNDAKA",
    "LEVEL_JEFFERSONBAY_RAIN",
    "LEVEL_MUNDAKA_CLOUDY",
    "LEVEL_CORTESBANK",
    "LEVEL_TEAHUPOO_NIGHT",
    "LEVEL_COSMOS",
};

