/*  THIS FILE IS AUTOMATICALLY GENERATED BY EXPORT FROM THE EXCEL FILE:  CAREERDATA.XLS
    ALL CHANGES SHOULD BE MADE IN EXCEL AND RE_EXPORTED.  DO NOT HAND EDIT.
    David Cook, Treyarch, 6/25/01
*/

#ifndef CAREERDATA_H
#define CAREERDATA_H

#define MAX_GOALS_PER_LEVEL  5 
#define MAX_PREV_LEVELS  4 
#define MAX_NEXT_LEVELS  2 

enum {
    LEVEL_INDOOR_1,
    LEVEL_INDOOR_2,
    LEVEL_INDOOR_3,
    LEVEL_SEBASTIAN_1,
    LEVEL_TRESTLES_1,
    LEVEL_TRESTLES_2,
    LEVEL_MAVERICKS_CLOUDY,
    LEVEL_MAVERICKS_OMINOUS,
    LEVEL_SEBASTIAN_2,
    LEVEL_ANTARCTICA_1,
    LEVEL_ANTARCTICA_2,
    LEVEL_JAWS,
    LEVEL_PIPELINE_1,
    LEVEL_JAWS_CLOUDY,
    LEVEL_TEAHUPOO,
    LEVEL_PIPELINE_2,
    LEVEL_TEAHUPOO_EVENING,
    LEVEL_BELLS,
    LEVEL_BELLS_NIGHT,
    LEVEL_CURRENSPOINT_1,
    LEVEL_KIRRA,
    LEVEL_KIRRA_EVENING,
    LEVEL_GLAND,
    LEVEL_GLAND_CLOUDY,
    LEVEL_CURRENSPOINT_2,
    LEVEL_JEFFERSONBAY,
    LEVEL_MUNDAKA,
    LEVEL_JEFFERSONBAY_RAIN,
    LEVEL_MUNDAKA_CLOUDY,
    LEVEL_CORTESBANK,
    LEVEL_TEAHUPOO_NIGHT,
    LEVEL_COSMOS,
    LEVEL_LAST
};

enum {
    GOAL_NOTHING,
    GOAL_BASIC_CONTROLS,
    GOAL_ICON_3D,
    GOAL_COMPETITION_1,
    GOAL_COMPETITION_2,
    GOAL_COMPETITION_3,
    GOAL_SPECIAL_METER,
    GOAL_PHOTO_1,
    GOAL_PHOTO_2,
    GOAL_PHOTO_3,
    GOAL_LOCAL,
    GOAL_LOCAL_2,
    GOAL_ICON_TETRIS,
    GOAL_SKILL_FACE,
    GOAL_SKILL_AIR,
    GOAL_SKILL_TUBE,
    GOAL_SKILL_360_SPIN,
    GOAL_SKILL_540_SPIN,
    GOAL_SCORE,
    GOAL_ENV_SPRAY_WINDSURFERS,
    GOAL_ENV_SMASH_ICE,
    GOAL_ENV_SPRAY_JETSKIERS,
    GOAL_ENV_SMASH_SPONGERS,
    GOAL_ENV_JUMP_TURTLES,
    GOAL_ENV_JUMP_KAYAKERS,
    GOAL_ENV_SPRAY_TUBERS,
    GOAL_ENV_SPRAY_RAFTERS,
    GOAL_ENV_JUMP_PIER,
    GOAL_SKILL_FACE_SCORE,
    GOAL_SKILL_AIR_SCORE,
    GOAL_SKILL_TUBE_SCORE,
    GOAL_SKILL_360_SPIN_SCORE,
    GOAL_SKILL_540_SPIN_SCORE,
    GOAL_LONGEST_RIDE,
    GOAL_LEARN_NEW_TRICK,
    GOAL_TUTORIAL_1,
    GOAL_TUTORIAL_2,
    GOAL_TUTORIAL_3,
    GOAL_LAST,
};

enum {
    REWARD_NOTHING,
    REWARD_LEVEL_BOARD,
    REWARD_PERSONALITY_SUIT,
    REWARD_POINTS,
    REWARD_SURFER_BOARD,
    REWARD_JUMP_POINTS,
    REWARD_SPEED_POINTS,
    REWARD_SPIN_POINTS,
    REWARD_BALANCE_POINTS,
    REWARD_CHEAT,
    REWARD_SURFER,
    REWARD_LEVEL_BOARD_AND_SURFER,
    REWARD_SURFER_MOVIE,
    REWARD_SPECIAL_TRICK,
    REWARD_LAST,
};

typedef struct CareerDataStruct {
    int beach;                                   // Which beach
    int goal_param[5];                           // Parameters for the goals
    int reward_param[5];                         // parameters for the reward
    char beach_file[32];                         // Which beach file to load
    char name[32];                               // the name used for setting the level by name
    int goal[5];                                 // Goals for this level
    int goal_param_2[5];                         // extra parameter for goals as needed
    int reward[5];                               // the reward for completing a goal
    int prev_levels[4];                          // previous levels in progression
    int next_levels[2];                          // next levels in progression
    float level_duration;                        // time per run in career mode
    char stash_name[15];                         // The level stash to load
    int use_ai_surfer;                           // Do we actually have an ai surfer
    char challenge_name[32];                     // heading for the challenge display
} CareerData, *CareerDataPtr;

extern CareerData CareerDataArray[];
extern stringx LevelNameArray[];
void CAREERDATA_Load(void);

#endif /* #ifndef CAREERDATA_H */
