// files for ps2 link speedup

// With precompiled headers enabled, all text up to and including 
// the following line are ignored by the compiler (dc 01/18/02)
#include "global.h"

//#include "ksfile.cpp"
#include "beach.cpp"
#include "beachdata.cpp"
#include "board.cpp"
#include "careerdata.cpp"
#include "DemoMode.cpp"
#include "floatobj.cpp"
#include "kellyslater_ai_goals.cpp"
#include "kellyslater_controller.cpp"
#include "kellyslater_main.cpp"
#include "ks_camera.cpp"
#include "ksdbmenu.cpp"
#include "ksreplay.cpp"
#include "menu.cpp"
#include "menungl.cpp"
#include "menusys.cpp"
#include "ode.cpp"
//#include "parser.cpp"
#include "physics.cpp"
#include "rumbleManager.cpp"
#include "spline.cpp"
#include "surferdata.cpp"
#include "text_parser.cpp"
#include "tricks.cpp"
#include "trick_system.cpp"
#include "ik_object.cpp"
#include "scoringmanager.cpp"
#include "specialmeter.cpp"
#include "wavesound.cpp"
#include "VOEngine.cpp"
#include "MusicMan.cpp"
#include "player.cpp"
#include "judge.cpp"
#include "career.cpp"
#include "SFXEngine.cpp"
//#include "WipeTransition.cpp"
#include "trickdata.cpp"
#include "tutorialdata.cpp"
#include "combodata.cpp"
#include "wipeoutdata.cpp"
#include "BoardManager.cpp"
#include "challenge.cpp"
#include "challenge_icon.cpp"
#include "challenge_photo.cpp"
#include "compressedphoto.cpp"
#include "cheat.cpp"
#include "dxt1_codebook.cpp"
#include "dxt1_gen.cpp"
#include "dxt1_imagedxt1.cpp"
#include "sounddata.cpp"