///   these anims are loaded from data\characters and are shared by all surfers
MAC(SURFER_ANIM_PLACEHOLDER, "PLACE HOLDER")
MAC(SURFER_DUMMY_ANIM1, "ALL_DUMMY_ANIM1")
MAC(SURFER_DUMMY_ANIM2, "ALL_DUMMY_ANIM2")
MAC(SURFER_DUMMY_ANIM3, "ALL_DUMMY_ANIM3")
MAC(SURFER_DUMMY_ANIM4, "ALL_DUMMY_ANIM4")
MAC(SURFER_DUMMY_ANIM5, "ALL_DUMMY_ANIM5")

MAC(SURFER_ANIM_STUMBLE_BACK, "ALL_BAS_STUMBLE_BACK")//
MAC(SURFER_ANIM_BAS_CROUCH, "ALL_BAS_CROUCH")//
MAC(SURFER_ANIM_BAS_L_CROUCH, "ALL_BAS_L_CROUCH")//
MAC(SURFER_ANIM_BAS_R_CROUCH, "ALL_BAS_R_CROUCH")//
MAC(SURFER_ANIM_TRANS_STAND_LIE_1, "ALL_TRANS_STAND_LIE_1")//
MAC(SURFER_ANIM_TRICKBOOK_CARVE, "ALL_TRICKBOOK_CARVE")

//  try to take out later, with Jem's approval
MAC(SURFER_ANIM_RIGHTGRABTURN, "ALL_BAS_R_GRAB")//
MAC(SURFER_ANIM_LEFTGRABTURN, "ALL_BAS_L_GRAB")//
MAC(SURFER_ANIM_BAS_WOBBLE_1, "ALL_BAS_WOBBLE_1")//

//  tricks without board anims
MAC(SURFER_ANIM_TRK_FACE_HANGTEN_1, "ALL_TRK_FACE_HANGTEN_1")
MAC(SURFER_ANIM_TRK_FACE_CHEATER5_1, "ALL_TRK_FACE_CHEATER5_1")
MAC(SURFER_ANIM_TRK_FACE_SITTER_1, "ALL_TRK_FACE_SITTER_1")
MAC(SURFER_ANIM_TRK_FACE_HEADSTAND_1, "ALL_TRK_FACE_HEADSTAND_1")
MAC(SURFER_ANIM_TRK_AERIAL_HOP_DOWN, "ALL_TRK_AERIAL_HOP_DOWN")//
MAC(SURFER_ANIM_AIR_JUNKLAND_1, "ALL_AIR_JUNKLAND_1")//
//MAC(SURFER_ANIM_TRK_FLOAT_TL_1, "ALL_TRK_FLOAT_TL_1")//
//MAC(SURFER_ANIM_TRK_FLOAT_TR_1, "ALL_TRK_FLOAT_TR_1")//
//MAC(SURFER_ANIM_TRK_FLOAT_TLL_1, "ALL_TRK_FLOAT_TLL_1")//
//MAC(SURFER_ANIM_TRK_FLOAT_TRR_1, "ALL_TRK_FLOAT_TRR_1")//
MAC(SURFER_ANIM_TRK_OUT_FLOAT_1, "ALL_TRK_OUT_FLOAT_1")//

MAC(SURFER_ANIM_TRK_TUBE_FS_L_5, "ALL_TRK_TUBE_FS_L_5")//
MAC(SURFER_ANIM_TRK_TUBE_FS_L_3, "ALL_TRK_TUBE_FS_L_3")//
MAC(SURFER_ANIM_TRK_TUBE_FS_L_1, "ALL_TRK_TUBE_FS_L_1")//
MAC(SURFER_ANIM_TRK_TUBE_FS_1,	 "ALL_TRK_TUBE_FS_1")//			Stand in the tube
MAC(SURFER_ANIM_TRK_TUBE_FS_R_1, "ALL_TRK_TUBE_FS_R_1")//
MAC(SURFER_ANIM_TRK_TUBE_FS_R_3, "ALL_TRK_TUBE_FS_R_3")//
MAC(SURFER_ANIM_TRK_TUBE_FS_R_5, "ALL_TRK_TUBE_FS_R_5")//

MAC(SURFER_ANIM_TRK_TUBE_SPEED_1_L_3, "ALL_TRK_TUBE_SPEED_1_L_3")//
MAC(SURFER_ANIM_TRK_TUBE_SPEED_1_L_2, "ALL_TRK_TUBE_SPEED_1_L_2")//
MAC(SURFER_ANIM_TRK_TUBE_SPEED_1_L_1, "ALL_TRK_TUBE_SPEED_1_L_1")//
MAC(SURFER_ANIM_TRK_TUBE_SPEED_1,	  "ALL_TRK_TUBE_SPEED_1")//			Move forward in the tube
MAC(SURFER_ANIM_TRK_TUBE_SPEED_1_R_1, "ALL_TRK_TUBE_SPEED_1_R_1")//
MAC(SURFER_ANIM_TRK_TUBE_SPEED_1_R_2, "ALL_TRK_TUBE_SPEED_1_R_2")//
MAC(SURFER_ANIM_TRK_TUBE_SPEED_1_R_3, "ALL_TRK_TUBE_SPEED_1_R_3")//

MAC(SURFER_ANIM_TRK_TUBE_FS_1ROOF_1_L_5, "ALL_TRK_TUBE_FS_1ROOF_1_L_5")//
MAC(SURFER_ANIM_TRK_TUBE_FS_1ROOF_1_L_3, "ALL_TRK_TUBE_FS_1ROOF_1_L_3")//
MAC(SURFER_ANIM_TRK_TUBE_FS_1ROOF_1_L_1, "ALL_TRK_TUBE_FS_1ROOF_1_L_1")//
MAC(SURFER_ANIM_TRK_TUBE_FS_1ROOF_1, "ALL_TRK_TUBE_FS_1ROOF_1")//			One Hand Roof Drag
MAC(SURFER_ANIM_TRK_TUBE_FS_1ROOF_1_R_1, "ALL_TRK_TUBE_FS_1ROOF_1_R_1")//
MAC(SURFER_ANIM_TRK_TUBE_FS_1ROOF_1_R_3, "ALL_TRK_TUBE_FS_1ROOF_1_R_3")//
MAC(SURFER_ANIM_TRK_TUBE_FS_1ROOF_1_R_5, "ALL_TRK_TUBE_FS_1ROOF_1_R_5")//

MAC(SURFER_ANIM_TRK_TUBE_FS_2ROOF_1_L_5, "ALL_TRK_TUBE_FS_2ROOF_1_L_5")//
MAC(SURFER_ANIM_TRK_TUBE_FS_2ROOF_1_L_3, "ALL_TRK_TUBE_FS_2ROOF_1_L_3")//
MAC(SURFER_ANIM_TRK_TUBE_FS_2ROOF_1_L_1, "ALL_TRK_TUBE_FS_2ROOF_1_L_1")//
MAC(SURFER_ANIM_TRK_TUBE_FS_2ROOF_1, "ALL_TRK_TUBE_FS_2ROOF_1")//			Two Hand Roof Drag
MAC(SURFER_ANIM_TRK_TUBE_FS_2ROOF_1_R_1, "ALL_TRK_TUBE_FS_2ROOF_1_R_1")//
MAC(SURFER_ANIM_TRK_TUBE_FS_2ROOF_1_R_3, "ALL_TRK_TUBE_FS_2ROOF_1_R_3")//
MAC(SURFER_ANIM_TRK_TUBE_FS_2ROOF_1_R_5, "ALL_TRK_TUBE_FS_2ROOF_1_R_5")//

MAC(SURFER_ANIM_TRK_TUBE_2OUT_L_5, "ALL_TRK_TUBE_2OUT_L_5")//
MAC(SURFER_ANIM_TRK_TUBE_2OUT_L_3, "ALL_TRK_TUBE_2OUT_L_3")//
MAC(SURFER_ANIM_TRK_TUBE_2OUT_L_1, "ALL_TRK_TUBE_2OUT_L_1")//
MAC(SURFER_ANIM_TRK_TUBE_2OUT, "ALL_TRK_TUBE_2OUT")		//  Christ Tube
MAC(SURFER_ANIM_TRK_TUBE_2OUT_R_1, "ALL_TRK_TUBE_2OUT_R_1")//
MAC(SURFER_ANIM_TRK_TUBE_2OUT_R_3, "ALL_TRK_TUBE_2OUT_R_3")//
MAC(SURFER_ANIM_TRK_TUBE_2OUT_R_5, "ALL_TRK_TUBE_2OUT_R_5")//

MAC(SURFER_ANIM_TRK_TUBE_LAYBACK_L_5, "ALL_TRK_TUBE_LAYBACK_L_5")//
MAC(SURFER_ANIM_TRK_TUBE_LAYBACK_L_3, "ALL_TRK_TUBE_LAYBACK_L_3")//
MAC(SURFER_ANIM_TRK_TUBE_LAYBACK_L_1, "ALL_TRK_TUBE_LAYBACK_L_1")//
MAC(SURFER_ANIM_TRK_TUBE_LAYBACK, "ALL_TRK_TUBE_LAYBACK")		//  Behind the back
MAC(SURFER_ANIM_TRK_TUBE_LAYBACK_R_1, "ALL_TRK_TUBE_LAYBACK_R_1")//
MAC(SURFER_ANIM_TRK_TUBE_LAYBACK_R_3, "ALL_TRK_TUBE_LAYBACK_R_3")//
MAC(SURFER_ANIM_TRK_TUBE_LAYBACK_R_5, "ALL_TRK_TUBE_LAYBACK_R_5")//

MAC(SURFER_ANIM_TRK_TUBE_LAYFORE_L_5, "ALL_TRK_TUBE_LAYFORE_L_5")//
MAC(SURFER_ANIM_TRK_TUBE_LAYFORE_L_3, "ALL_TRK_TUBE_LAYFORE_L_3")//
MAC(SURFER_ANIM_TRK_TUBE_LAYFORE_L_1, "ALL_TRK_TUBE_LAYFORE_L_1")//
MAC(SURFER_ANIM_TRK_TUBE_LAYFORE, "ALL_TRK_TUBE_LAYFORE")		//  Behind the back, other hand
MAC(SURFER_ANIM_TRK_TUBE_LAYFORE_R_1, "ALL_TRK_TUBE_LAYFORE_R_1")//
MAC(SURFER_ANIM_TRK_TUBE_LAYFORE_R_3, "ALL_TRK_TUBE_LAYFORE_R_3")//
MAC(SURFER_ANIM_TRK_TUBE_LAYFORE_R_5, "ALL_TRK_TUBE_LAYFORE_R_5")//

MAC(SURFER_ANIM_TRK_TUBE_FS_1OUT_L_1_L_5, "ALL_TRK_TUBE_FS_1OUT_L_L_5")//
MAC(SURFER_ANIM_TRK_TUBE_FS_1OUT_L_1_L_3, "ALL_TRK_TUBE_FS_1OUT_L_L_3")//
MAC(SURFER_ANIM_TRK_TUBE_FS_1OUT_L_1_L_1, "ALL_TRK_TUBE_FS_1OUT_L_L_1")//
MAC(SURFER_ANIM_TRK_TUBE_FS_1OUT_L_1, "ALL_TRK_TUBE_FS_1OUT_L_1")//      Left handed one hand drag
MAC(SURFER_ANIM_TRK_TUBE_FS_1OUT_L_1_R_1, "ALL_TRK_TUBE_FS_1OUT_L_R_1")//
MAC(SURFER_ANIM_TRK_TUBE_FS_1OUT_L_1_R_3, "ALL_TRK_TUBE_FS_1OUT_L_R_3")//
MAC(SURFER_ANIM_TRK_TUBE_FS_1OUT_L_1_R_5, "ALL_TRK_TUBE_FS_1OUT_L_R_5")//

MAC(SURFER_ANIM_TRK_TUBE_FS_1OUT_R_1_L_5, "ALL_TRK_TUBE_FS_1OUT_R_L_5")//
MAC(SURFER_ANIM_TRK_TUBE_FS_1OUT_R_1_L_3, "ALL_TRK_TUBE_FS_1OUT_R_L_3")//
MAC(SURFER_ANIM_TRK_TUBE_FS_1OUT_R_1_L_1, "ALL_TRK_TUBE_FS_1OUT_R_L_1")//
MAC(SURFER_ANIM_TRK_TUBE_FS_1OUT_R_1, "ALL_TRK_TUBE_FS_1OUT_R_1")//      Right handed one hand drag
MAC(SURFER_ANIM_TRK_TUBE_FS_1OUT_R_1_R_1, "ALL_TRK_TUBE_FS_1OUT_R_R_1")//
MAC(SURFER_ANIM_TRK_TUBE_FS_1OUT_R_1_R_3, "ALL_TRK_TUBE_FS_1OUT_R_R_3")//
MAC(SURFER_ANIM_TRK_TUBE_FS_1OUT_R_1_R_5, "ALL_TRK_TUBE_FS_1OUT_R_R_5")//

MAC(SURFER_ANIM_TRK_TUBE_FS_2DOWN_1_L_5, "ALL_TRK_TUBE_FS_2DOWN_L_5")//
MAC(SURFER_ANIM_TRK_TUBE_FS_2DOWN_1_L_3, "ALL_TRK_TUBE_FS_2DOWN_L_3")//
MAC(SURFER_ANIM_TRK_TUBE_FS_2DOWN_1_L_1, "ALL_TRK_TUBE_FS_2DOWN_L_1")//
MAC(SURFER_ANIM_TRK_TUBE_FS_2DOWN_1, "ALL_TRK_TUBE_FS_2DOWN_1")//		Two Hand drag
MAC(SURFER_ANIM_TRK_TUBE_FS_2DOWN_1_R_1, "ALL_TRK_TUBE_FS_2DOWN_R_1")//
MAC(SURFER_ANIM_TRK_TUBE_FS_2DOWN_1_R_3, "ALL_TRK_TUBE_FS_2DOWN_R_3")//
MAC(SURFER_ANIM_TRK_TUBE_FS_2DOWN_1_R_5, "ALL_TRK_TUBE_FS_2DOWN_R_5")//

MAC(SURFER_ANIM_TRK_TUBE_GRAB_DRAG_R_L_5, "ALL_TRK_TUBE_DRAG_R_L_5")//
MAC(SURFER_ANIM_TRK_TUBE_GRAB_DRAG_R_L_3, "ALL_TRK_TUBE_DRAG_R_L_3")//
MAC(SURFER_ANIM_TRK_TUBE_GRAB_DRAG_R_L_1, "ALL_TRK_TUBE_DRAG_R_L_1")//
MAC(SURFER_ANIM_TRK_TUBE_GRAB_DRAG_R_1, "ALL_TRK_TUBE_DRAG_R_1")//   Tube grab rail and drag right
MAC(SURFER_ANIM_TRK_TUBE_GRAB_DRAG_R_R_1, "ALL_TRK_TUBE_DRAG_R_R_1")//
MAC(SURFER_ANIM_TRK_TUBE_GRAB_DRAG_R_R_3, "ALL_TRK_TUBE_DRAG_R_R_3")//
MAC(SURFER_ANIM_TRK_TUBE_GRAB_DRAG_R_R_5, "ALL_TRK_TUBE_DRAG_R_R_5")//

MAC(SURFER_ANIM_TRK_TUBE_GRAB_DRAG_L_L_5, "ALL_TRK_TUBE_DRAG_L_L_5")//
MAC(SURFER_ANIM_TRK_TUBE_GRAB_DRAG_L_L_3, "ALL_TRK_TUBE_DRAG_L_L_3")//
MAC(SURFER_ANIM_TRK_TUBE_GRAB_DRAG_L_L_1, "ALL_TRK_TUBE_DRAG_L_L_1")//
MAC(SURFER_ANIM_TRK_TUBE_GRAB_DRAG_L_1, "ALL_TRK_TUBE_DRAG_L_1")//   Tube grab and drag rail left
MAC(SURFER_ANIM_TRK_TUBE_GRAB_DRAG_L_R_1, "ALL_TRK_TUBE_DRAG_L_R_1")//
MAC(SURFER_ANIM_TRK_TUBE_GRAB_DRAG_L_R_3, "ALL_TRK_TUBE_DRAG_L_R_3")//
MAC(SURFER_ANIM_TRK_TUBE_GRAB_DRAG_L_R_5, "ALL_TRK_TUBE_DRAG_L_R_5")//

MAC(SURFER_ANIM_TRK_TUBE_GRAB_R_L_5, "ALL_TRK_TUBE_GRAB_R_L_5")//
MAC(SURFER_ANIM_TRK_TUBE_GRAB_R_L_3, "ALL_TRK_TUBE_GRAB_R_L_3")//
MAC(SURFER_ANIM_TRK_TUBE_GRAB_R_L_1, "ALL_TRK_TUBE_GRAB_R_L_1")//
MAC(SURFER_ANIM_TRK_TUBE_GRAB_R_1, "ALL_TRK_TUBE_GRAB_R_1")//   Tube grab rail right
MAC(SURFER_ANIM_TRK_TUBE_GRAB_R_R_1, "ALL_TRK_TUBE_GRAB_R_R_1")//
MAC(SURFER_ANIM_TRK_TUBE_GRAB_R_R_3, "ALL_TRK_TUBE_GRAB_R_R_3")//
MAC(SURFER_ANIM_TRK_TUBE_GRAB_R_R_5, "ALL_TRK_TUBE_GRAB_R_R_5")//

MAC(SURFER_ANIM_TRK_TUBE_GRAB_L_L_5, "ALL_TRK_TUBE_GRAB_L_L_5")//
MAC(SURFER_ANIM_TRK_TUBE_GRAB_L_L_3, "ALL_TRK_TUBE_GRAB_L_L_3")//
MAC(SURFER_ANIM_TRK_TUBE_GRAB_L_L_1, "ALL_TRK_TUBE_GRAB_L_L_1")//
MAC(SURFER_ANIM_TRK_TUBE_GRAB_L_1, "ALL_TRK_TUBE_GRAB_L_1")//   Tube grab rail left
MAC(SURFER_ANIM_TRK_TUBE_GRAB_L_R_1, "ALL_TRK_TUBE_GRAB_L_R_1")//
MAC(SURFER_ANIM_TRK_TUBE_GRAB_L_R_3, "ALL_TRK_TUBE_GRAB_L_R_3")//
MAC(SURFER_ANIM_TRK_TUBE_GRAB_L_R_5, "ALL_TRK_TUBE_GRAB_L_R_5")//

MAC(SURFER_ANIM_TRK_TUBE_LEGDRG_L_L_5, "ALL_TRK_TUBE_LEGDRG_L_L_5")//
MAC(SURFER_ANIM_TRK_TUBE_LEGDRG_L_L_3, "ALL_TRK_TUBE_LEGDRG_L_L_3")//
MAC(SURFER_ANIM_TRK_TUBE_LEGDRG_L_L_1, "ALL_TRK_TUBE_LEGDRG_L_L_1")//
MAC(SURFER_ANIM_TRK_TUBE_LEGDRG_L_1, "ALL_TRK_TUBE_LEGDRG_L_1")//		Foot Drag
MAC(SURFER_ANIM_TRK_TUBE_LEGDRG_L_R_1, "ALL_TRK_TUBE_LEGDRG_L_R_1")//
MAC(SURFER_ANIM_TRK_TUBE_LEGDRG_L_R_3, "ALL_TRK_TUBE_LEGDRG_L_R_3")//
MAC(SURFER_ANIM_TRK_TUBE_LEGDRG_L_R_5, "ALL_TRK_TUBE_LEGDRG_L_R_5")//

MAC(SURFER_ANIM_TRK_TUBE_LEGDRG_R_L_5, "ALL_TRK_TUBE_LEGDRG_R_L_5")//
MAC(SURFER_ANIM_TRK_TUBE_LEGDRG_R_L_3, "ALL_TRK_TUBE_LEGDRG_R_L_3")//
MAC(SURFER_ANIM_TRK_TUBE_LEGDRG_R_L_1, "ALL_TRK_TUBE_LEGDRG_R_L_1")//
MAC(SURFER_ANIM_TRK_TUBE_LEGDRG_R_1, "ALL_TRK_TUBE_LEGDRG_R_1")//			Foot Drag, other side
MAC(SURFER_ANIM_TRK_TUBE_LEGDRG_R_R_1, "ALL_TRK_TUBE_LEGDRG_R_R_1")//
MAC(SURFER_ANIM_TRK_TUBE_LEGDRG_R_R_3, "ALL_TRK_TUBE_LEGDRG_R_R_3")//
MAC(SURFER_ANIM_TRK_TUBE_LEGDRG_R_R_5, "ALL_TRK_TUBE_LEGDRG_R_R_5")//

MAC(SURFER_ANIM_TRK_TUBE_SPITOUT_L_5, "ALL_TRK_TUBE_SPITOUT_L_5")//
MAC(SURFER_ANIM_TRK_TUBE_SPITOUT_L_3, "ALL_TRK_TUBE_SPITOUT_L_3")//
MAC(SURFER_ANIM_TRK_TUBE_SPITOUT_L_1, "ALL_TRK_TUBE_SPITOUT_L_1")//
MAC(SURFER_ANIM_TRK_TUBE_SPITOUT_1, "ALL_TRK_TUBE_SPITOUT_1")//			Blown Out
MAC(SURFER_ANIM_TRK_TUBE_SPITOUT_R_1, "ALL_TRK_TUBE_SPITOUT_R_1")//
MAC(SURFER_ANIM_TRK_TUBE_SPITOUT_R_3, "ALL_TRK_TUBE_SPITOUT_R_3")//
MAC(SURFER_ANIM_TRK_TUBE_SPITOUT_R_5, "ALL_TRK_TUBE_SPITOUT_R_5")//

MAC(SURFER_ANIM_TRK_TUBE_FS_COFFIN, "ALL_TRK_TUBE_FS_COFFIN")//
MAC(SURFER_ANIM_TRK_TUBE_CAVEMAN, "ALL_TRK_TUBE_CAVEMAN")//
MAC(SURFER_ANIM_TRK_TUBE_LAWNDART, "ALL_TRK_TUBE_LAWNDART")//

MAC(SURFER_ANIM_TRN_GRAB_L_1, "ALL_TRN_GRAB_L_1")//
MAC(SURFER_ANIM_TRN_GRAB_L_2, "ALL_TRN_GRAB_L_2")//
MAC(SURFER_ANIM_TRN_GRAB_L_3, "ALL_TRN_GRAB_L_3")//
MAC(SURFER_ANIM_TRN_GRAB_L_4, "ALL_TRN_GRAB_L_4")//
MAC(SURFER_ANIM_TRN_GRAB_L_5, "ALL_TRN_GRAB_L_5")//
MAC(SURFER_ANIM_TRN_GRAB_L_6, "ALL_TRN_GRAB_L_6")//
MAC(SURFER_ANIM_TRN_GRAB_L_7, "ALL_TRN_GRAB_L_7")//
MAC(SURFER_ANIM_TRN_GRAB_L_8, "ALL_TRN_GRAB_L_8")//
MAC(SURFER_ANIM_TRN_GRAB_L_9, "ALL_TRN_GRAB_L_9")//
MAC(SURFER_ANIM_TRN_GRAB_R_1, "ALL_TRN_GRAB_R_1")//
MAC(SURFER_ANIM_TRN_GRAB_R_2, "ALL_TRN_GRAB_R_2")//
MAC(SURFER_ANIM_TRN_GRAB_R_3, "ALL_TRN_GRAB_R_3")//
MAC(SURFER_ANIM_TRN_GRAB_R_4, "ALL_TRN_GRAB_R_4")//
MAC(SURFER_ANIM_TRN_GRAB_R_5, "ALL_TRN_GRAB_R_5")//
MAC(SURFER_ANIM_TRN_GRAB_R_6, "ALL_TRN_GRAB_R_6")//
MAC(SURFER_ANIM_TRN_GRAB_R_7, "ALL_TRN_GRAB_R_7")//
MAC(SURFER_ANIM_TRN_GRAB_R_8, "ALL_TRN_GRAB_R_8")//
MAC(SURFER_ANIM_TRN_GRAB_R_9, "ALL_TRN_GRAB_R_9")//

//MAC(SURFER_ANIM_TRK_FLOAT_B_L_5, "ALL_TRK_FLOAT_B_L_5")//
//MAC(SURFER_ANIM_TRK_FLOAT_B_L_4, "ALL_TRK_FLOAT_B_L_4")//
//MAC(SURFER_ANIM_TRK_FLOAT_B_L_3, "ALL_TRK_FLOAT_B_L_3")//
//MAC(SURFER_ANIM_TRK_FLOAT_B_L_2, "ALL_TRK_FLOAT_B_L_2")//
//MAC(SURFER_ANIM_TRK_FLOAT_B_L_1, "ALL_TRK_FLOAT_B_L_1")//
MAC(SURFER_ANIM_TRK_FLOAT_B_C_1, "ALL_TRK_FLOAT_B_C_1")//
//MAC(SURFER_ANIM_TRK_FLOAT_B_R_1, "ALL_TRK_FLOAT_B_R_1")//
//MAC(SURFER_ANIM_TRK_FLOAT_B_R_2, "ALL_TRK_FLOAT_B_R_2")//
//MAC(SURFER_ANIM_TRK_FLOAT_B_R_3, "ALL_TRK_FLOAT_B_R_3")//
//MAC(SURFER_ANIM_TRK_FLOAT_B_R_4, "ALL_TRK_FLOAT_B_R_4")//
//MAC(SURFER_ANIM_TRK_FLOAT_B_R_5, "ALL_TRK_FLOAT_B_R_5")//

//MAC(SURFER_ANIM_TRK_FLOAT_F_L_5, "ALL_TRK_FLOAT_F_L_5")//
//MAC(SURFER_ANIM_TRK_FLOAT_F_L_4, "ALL_TRK_FLOAT_F_L_4")//
//MAC(SURFER_ANIM_TRK_FLOAT_F_L_3, "ALL_TRK_FLOAT_F_L_3")//
//MAC(SURFER_ANIM_TRK_FLOAT_F_L_2, "ALL_TRK_FLOAT_F_L_2")//
//MAC(SURFER_ANIM_TRK_FLOAT_F_L_1, "ALL_TRK_FLOAT_F_L_1")//
MAC(SURFER_ANIM_TRK_FLOAT_F_C_1, "ALL_TRK_FLOAT_F_C_1")//
//MAC(SURFER_ANIM_TRK_FLOAT_F_R_1, "ALL_TRK_FLOAT_F_R_1")//
//MAC(SURFER_ANIM_TRK_FLOAT_F_R_2, "ALL_TRK_FLOAT_F_R_2")//
//MAC(SURFER_ANIM_TRK_FLOAT_F_R_3, "ALL_TRK_FLOAT_F_R_3")//
//MAC(SURFER_ANIM_TRK_FLOAT_F_R_4, "ALL_TRK_FLOAT_F_R_4")//
//MAC(SURFER_ANIM_TRK_FLOAT_F_R_5, "ALL_TRK_FLOAT_F_R_5")//

//MAC(SURFER_ANIM_TRK_FLOAT_L_L_5, "ALL_TRK_FLOAT_L_L_5")//
//MAC(SURFER_ANIM_TRK_FLOAT_L_L_4, "ALL_TRK_FLOAT_L_L_4")//
//MAC(SURFER_ANIM_TRK_FLOAT_L_L_3, "ALL_TRK_FLOAT_L_L_3")//
//MAC(SURFER_ANIM_TRK_FLOAT_L_L_2, "ALL_TRK_FLOAT_L_L_2")//
//MAC(SURFER_ANIM_TRK_FLOAT_L_L_1, "ALL_TRK_FLOAT_L_L_1")//
MAC(SURFER_ANIM_TRK_FLOAT_L_C_1, "ALL_TRK_FLOAT_L_C_1")//
//MAC(SURFER_ANIM_TRK_FLOAT_L_R_1, "ALL_TRK_FLOAT_L_R_1")//
//MAC(SURFER_ANIM_TRK_FLOAT_L_R_2, "ALL_TRK_FLOAT_L_R_2")//
//MAC(SURFER_ANIM_TRK_FLOAT_L_R_3, "ALL_TRK_FLOAT_L_R_3")//
//MAC(SURFER_ANIM_TRK_FLOAT_L_R_4, "ALL_TRK_FLOAT_L_R_4")//
//MAC(SURFER_ANIM_TRK_FLOAT_L_R_5, "ALL_TRK_FLOAT_L_R_5")//

//MAC(SURFER_ANIM_TRK_FLOAT_R_L_5, "ALL_TRK_FLOAT_R_L_5")//
//MAC(SURFER_ANIM_TRK_FLOAT_R_L_4, "ALL_TRK_FLOAT_R_L_4")//
//MAC(SURFER_ANIM_TRK_FLOAT_R_L_3, "ALL_TRK_FLOAT_R_L_3")//
//MAC(SURFER_ANIM_TRK_FLOAT_R_L_2, "ALL_TRK_FLOAT_R_L_2")//
//MAC(SURFER_ANIM_TRK_FLOAT_R_L_1, "ALL_TRK_FLOAT_R_L_1")//
MAC(SURFER_ANIM_TRK_FLOAT_R_C_1, "ALL_TRK_FLOAT_R_C_1")//
//MAC(SURFER_ANIM_TRK_FLOAT_R_R_1, "ALL_TRK_FLOAT_R_R_1")//
//MAC(SURFER_ANIM_TRK_FLOAT_R_R_2, "ALL_TRK_FLOAT_R_R_2")//
//MAC(SURFER_ANIM_TRK_FLOAT_R_R_3, "ALL_TRK_FLOAT_R_R_3")//
//MAC(SURFER_ANIM_TRK_FLOAT_R_R_4, "ALL_TRK_FLOAT_R_R_4")//
//MAC(SURFER_ANIM_TRK_FLOAT_R_R_5, "ALL_TRK_FLOAT_R_R_5")//

//  Tricks with board anims
MAC(SURFER_ANIM_TRK_AERIAL_180, "ALL_TRK_AERIAL_180")//
MAC(SURFER_ANIM_TRK_AERIAL_360, "ALL_TRK_AERIAL_360")//
MAC(SURFER_ANIM_AIR_JUDO, "ALL_AIR_JUDO")//
MAC(SURFER_ANIM_AIR_INDY, "ALL_AIR_INDY")//
MAC(SURFER_ANIM_AIR_LIEN, "ALL_AIR_LIEN")//
MAC(SURFER_ANIM_AIR_MELON, "ALL_AIR_MELON")//
MAC(SURFER_ANIM_AIR_MUTE_GRAB, "ALL_AIR_MUTE_GRAB")//
MAC(SURFER_ANIM_AIR_NOSE_GRAB, "ALL_AIR_NOSE_GRAB")//
MAC(SURFER_ANIM_AIR_NUCLEAR, "ALL_AIR_NUCLEAR")//
MAC(SURFER_ANIM_AIR_SHOVETHIS, "ALL_AIR_SHOVETHIS_1")//
MAC(SURFER_ANIM_AIR_ROCKET_GRAB, "ALL_AIR_ROCKET_GRAB")//
MAC(SURFER_ANIM_AIR_STALEFISH, "ALL_AIR_STALEFISH")//
MAC(SURFER_ANIM_AIR_TAIL_GRAB, "ALL_AIR_TAIL_GRAB")//
MAC(SURFER_ANIM_AIR_ROASTBEEF, "ALL_AIR_ROASTBEEF")//
MAC(SURFER_ANIM_ALL_AIR_HEELFLIP_1, "ALL_AIR_HEELFLIP_1")//
MAC(SURFER_ANIM_ALL_AIR_FLIP_B_1, "ALL_AIR_FLIP_B_1")//
MAC(SURFER_ANIM_ALL_AIR_FLIP_F_1, "ALL_AIR_FLIP_F_1")//
MAC(SURFER_ANIM_ALL_AIR_FLIP_L_1, "ALL_AIR_FLIP_L_1")//
MAC(SURFER_ANIM_ALL_AIR_FLIP_R_1, "ALL_AIR_FLIP_R_1")//
MAC(SURFER_ANIM_ALL_AIR_KICKFLIP_1, "ALL_AIR_KICKFLIP_1")//
MAC(SURFER_ANIM_ALL_AIR_RODEO_1, "ALL_AIR_RODEO_1")//
MAC(SURFER_ANIM_ALL_AIR_SUNCHILD_1, "ALL_AIR_SUNCHILD_1")//
MAC(SURFER_ANIM_AIR_HELI_720_1, "ALL_AIR_HELI_720_1")//
MAC(SURFER_ANIM_AIR_ALLEY_OOP_1, "ALL_AIR_ALLEY_OOP_1")//
MAC(SURFER_ANIM_AIR_HANGMAN_1, "ALL_AIR_HANGMAN_1")//
MAC(SURFER_ANIM_AIR_MONKEYMAN, "ALL_AIR_MONKEYMAN")//
MAC(SURFER_ANIM_AIR_WALK_1, "ALL_AIR_WALK_1")//
MAC(SURFER_ANIM_AIR_SUPERMAN_1, "ALL_AIR_SUPERMAN_1")//
MAC(SURFER_ANIM_AIR_TWEAKER_1, "ALL_AIR_TWEAKER_1")//
MAC(SURFER_ANIM_AIR_NACNAC_1, "ALL_AIR_NACNAC_1")//
MAC(SURFER_ANIM_AIR_SHOVEIT_1, "ALL_AIR_SHOVEIT_1")//
MAC(SURFER_ANIM_AIR_METHOD, "ALL_AIR_METHOD")//
MAC(SURFER_ANIM_AIR_INDIAN_1, "ALL_AIR_INDIAN_1")//
MAC(SURFER_ANIM_AIR_CHANGMAN_1, "ALL_AIR_CHANGMAN_1")//

//  don't change the order for exit moves
MAC(SURFER_ANIM_AIR_EXIT_1, "ALL_AIR_EXIT_1")//
MAC(SURFER_ANIM_AIR_EXIT_11, "ALL_AIR_EXIT_11")//
MAC(SURFER_ANIM_AIR_EXIT_2, "ALL_AIR_EXIT_2")//
MAC(SURFER_ANIM_AIR_EXIT_21, "ALL_AIR_EXIT_21")//
MAC(SURFER_ANIM_AIR_EXIT_3, "ALL_AIR_EXIT_3")//
MAC(SURFER_ANIM_AIR_EXIT_31, "ALL_AIR_EXIT_31")//
MAC(SURFER_ANIM_AIR_EXIT_4, "ALL_AIR_EXIT_4")//
MAC(SURFER_ANIM_AIR_EXIT_41, "ALL_AIR_EXIT_41")//
MAC(SURFER_ANIM_AIR_EXIT_5, "ALL_AIR_EXIT_5")//
MAC(SURFER_ANIM_AIR_EXIT_51, "ALL_AIR_EXIT_51")//
MAC(SURFER_ANIM_AIR_EXIT_6, "ALL_AIR_EXIT_6")//
MAC(SURFER_ANIM_AIR_EXIT_61, "ALL_AIR_EXIT_61")//
MAC(SURFER_ANIM_AIR_EXIT_7, "ALL_AIR_EXIT_7")//
MAC(SURFER_ANIM_AIR_EXIT_71, "ALL_AIR_EXIT_71")//
MAC(SURFER_ANIM_AIR_EXIT_8, "ALL_AIR_EXIT_8")//
MAC(SURFER_ANIM_AIR_EXIT_81, "ALL_AIR_EXIT_81")//
//  end exit moves

MAC(SURFER_ANIM_TRK_FACE_SHOVEIT_1, "ALL_TRK_FACE_SHOVEIT_1")
MAC(SURFER_ANIM_TRK_FACE_DARKSLIDE_1, "ALL_TRK_FACE_DARKSLIDE_1")
MAC(SURFER_ANIM_TRK_FACE_MANUAL_1, "ALL_TRK_FACE_MANUAL_1")
MAC(SURFER_ANIM_TRK_FLOAT_L_1, "ALL_TRK_FLOAT_L_1")//
MAC(SURFER_ANIM_TRK_FLOAT_R_1, "ALL_TRK_FLOAT_R_1")//
MAC(SURFER_ANIM_TRK_INTO_FLOAT_1, "ALL_TRK_INTO_FLOAT_1")//
MAC(SURFER_ANIM_TRN_SNAP_L_1, "ALL_TRN_SNAP_L_1")//
MAC(SURFER_ANIM_TRN_SNAP_R_1, "ALL_TRN_SNAP_R_1")//
MAC(SURFER_ANIM_TRK_CUTBACK_L_1, "ALL_TRK_CUTBACK_L_1")
MAC(SURFER_ANIM_TRK_CUTBACK_R_1, "ALL_TRK_CUTBACK_R_1")
MAC(SURFER_ANIM_TRK_CUTBACK_L_11, "ALL_TRK_CUTBACK_L_11")
MAC(SURFER_ANIM_TRK_CUTBACK_R_11, "ALL_TRK_CUTBACK_R_11")
MAC(SURFER_ANIM_TRK_CUTBACK_L_2, "ALL_TRK_CUTBACK_L_2")
MAC(SURFER_ANIM_TRK_CUTBACK_R_2, "ALL_TRK_CUTBACK_R_2")
MAC(SURFER_ANIM_TRK_CUTBACK_L_21, "ALL_TRK_CUTBACK_L_21")
MAC(SURFER_ANIM_TRK_CUTBACK_R_21, "ALL_TRK_CUTBACK_R_21")
MAC(SURFER_ANIM_TRK_CUTBACK_L_3, "ALL_TRK_CUTBACK_L_3")
MAC(SURFER_ANIM_TRK_CUTBACK_R_3, "ALL_TRK_CUTBACK_R_3")
MAC(SURFER_ANIM_TRK_CUTBACK_L_31, "ALL_TRK_CUTBACK_L_31")
MAC(SURFER_ANIM_TRK_CUTBACK_R_31, "ALL_TRK_CUTBACK_R_31")
MAC(SURFER_ANIM_TRK_CUTBACK_L_4, "ALL_TRK_CUTBACK_L_4")
MAC(SURFER_ANIM_TRK_CUTBACK_R_4, "ALL_TRK_CUTBACK_R_4")
MAC(SURFER_ANIM_TRK_CUTBACK_L_41, "ALL_TRK_CUTBACK_L_41")
MAC(SURFER_ANIM_TRK_CUTBACK_R_41, "ALL_TRK_CUTBACK_R_41")
MAC(SURFER_ANIM_TRK_CUTBACK_L_5, "ALL_TRK_CUTBACK_L_5")
MAC(SURFER_ANIM_TRK_CUTBACK_R_5, "ALL_TRK_CUTBACK_R_5")
MAC(SURFER_ANIM_TRK_CUTBACK_L_51, "ALL_TRK_CUTBACK_L_51")
MAC(SURFER_ANIM_TRK_CUTBACK_R_51, "ALL_TRK_CUTBACK_R_51")
MAC(SURFER_ANIM_BAS_DUCKDIVE_DOWN_1, "ALL_BAS_DUCKDIVE_DOWN_1")//
MAC(SURFER_ANIM_BAS_DUCKDIVE_IDLE_1, "ALL_BAS_DUCKDIVE_IDLE_1")//
MAC(SURFER_ANIM_BAS_DUCKDIVE_UP_1, "ALL_BAS_DUCKDIVE_UP_1")//
MAC(SURFER_ANIM_CROUCH_SPD_1, "ALL_BAS_CROUCH_SPD_1")//
MAC(SURFER_ANIM_STALL, "ALL_BAS_STALL")
MAC(SURFER_ANIM_SLOW_STALL, "ALL_BAS_SLOW_STALL")  //  Short Stall, for when too far from the tube
MAC(SURFER_ANIM_SUPER_STALL_1, "ALL_BAS_SUPER_STALL_1")			//  out of tube super stall
MAC(SURFER_ANIM_TRK_TUBE_FS_SUPERSTALL_1, "ALL_TRK_TUBE_FS_SUPERSTALL_1")		//  And in-tube super stall.	
MAC(SURFER_ANIM_IDLE_LAYING, "ALL_IDLE_LAYING")//
MAC(SURFER_ANIM_LIE_PADDLE, "ALL_LIE_PADDEL")//
MAC(SURFER_ANIM_LIE_PADDLE_BK, "ALL_LIE_PADDEL_BK_1")//
MAC(SURFER_ANIM_LIE_PADDEL_L_1, "ALL_LIE_PADDEL_L_1")//
MAC(SURFER_ANIM_LIE_PADDEL_R_1, "ALL_LIE_PADDEL_R_1")//
//MAC(SURFER_TRANS_GET_ON_BOARD_1, "ALL_TRANS_GET_ON_BOARD_1")  //  From swimming to lying on the board.
MAC(SURFER_TRANS_GET_ON_BOARD_1, "ALL_W_GOB")  //  From swimming to lying on the board.
MAC(SURFER_ANIM_TRN_INVERT_1, "ALL_TRN_INVERT_1")
MAC(SURFER_ANIM_TAKE_OFF_WEAK_1, "ALL_TAKE_OFF_WEAK_1")//
MAC(SURFER_ANIM_TAKE_OFF_REG_1, "ALL_TAKE_OFF_REG_1")//
MAC(SURFER_ANIM_TAKE_OFF_LATE_1, "ALL_TAKE_OFF_LATE_1")//
MAC(SURFER_ANIM_TAKE_OFF_LATE_FK_1, "ALL_TAKE_OFF_LATE_FK_1")//
MAC(SURFER_ANIM_TRN_L_TAILSLIDE_1, "ALL_TRN_L_TAILSLIDE_1")//
MAC(SURFER_ANIM_TRN_R_TAILSLIDE_1, "ALL_TRN_R_TAILSLIDE_1")//
MAC(SURFER_ANIM_TRN_L_TAILSLIDE_2, "ALL_TRN_L_TAILSLIDE_2")//
MAC(SURFER_ANIM_TRN_R_TAILSLIDE_2, "ALL_TRN_R_TAILSLIDE_2")//
MAC(SURFER_ANIM_IDLE_ON_AIR, "ALL_IDLE_ON_AIR")//
MAC(SURFER_ANIM_FREEFALL, "ALL_BAS_FREEFALL_1")//
MAC(SURFER_ANIM_TRK_TUBE_QCUT_L_1, "ALL_TRK_TUBE_QCUT_L_1")//
MAC(SURFER_ANIM_TRK_TUBE_QCUT_R_1, "ALL_TRK_TUBE_QCUT_R_1")//
MAC(SURFER_ANIM_TRK_FACE_CRUZER_1, "ALL_TRK_FACE_CRUZER_1")
MAC(SURFER_ANIM_TRK_AERIAL_HOP_UP, "ALL_TRK_AERIAL_HOP_UP")//

// Wipeouts
MAC(SURFER_ANIM_W_1_AIR_R_DIS, "ALL_W_1_AIR_R_DIS")
MAC(SURFER_ANIM_W_1_AIR_R_FRF, "ALL_W_1_AIR_R_FRF")
MAC(SURFER_ANIM_W_1_AIR_R_IMP, "ALL_W_1_AIR_R_IMP")
MAC(SURFER_ANIM_W_1_AIR_BR_DIS, "ALL_W_1_AIR_BR_DIS")
MAC(SURFER_ANIM_W_1_AIR_BR_FRF, "ALL_W_1_AIR_BR_FRF")
MAC(SURFER_ANIM_W_1_AIR_BR_IMP, "ALL_W_1_AIR_BR_IMP")
MAC(SURFER_ANIM_W_1_AIR_FR_DIS, "ALL_W_1_AIR_FR_DIS")
MAC(SURFER_ANIM_W_1_AIR_FR_FRF, "ALL_W_1_AIR_FR_FRF")
MAC(SURFER_ANIM_W_1_AIR_FR_IMP, "ALL_W_1_AIR_FR_IMP")
MAC(SURFER_ANIM_W_1_AIR_L_DIS, "ALL_W_1_AIR_L_DIS")
MAC(SURFER_ANIM_W_1_AIR_L_FRF, "ALL_W_1_AIR_L_FRF")
MAC(SURFER_ANIM_W_1_AIR_L_IMP, "ALL_W_1_AIR_L_IMP")
MAC(SURFER_ANIM_W_1_AIR_BL_DIS, "ALL_W_1_AIR_BL_DIS")
MAC(SURFER_ANIM_W_1_AIR_BL_FRF, "ALL_W_1_AIR_BL_FRF")
MAC(SURFER_ANIM_W_1_AIR_BL_IMP, "ALL_W_1_AIR_BL_IMP")
MAC(SURFER_ANIM_W_1_AIR_FL_DIS, "ALL_W_1_AIR_FL_DIS")
MAC(SURFER_ANIM_W_1_AIR_FL_FRF, "ALL_W_1_AIR_FL_FRF")
MAC(SURFER_ANIM_W_1_AIR_FL_IMP, "ALL_W_1_AIR_FL_IMP")
MAC(SURFER_ANIM_W_1_AIR_B_DIS, "ALL_W_1_AIR_B_DIS")
MAC(SURFER_ANIM_W_1_AIR_B_FRF, "ALL_W_1_AIR_B_FRF")
MAC(SURFER_ANIM_W_1_AIR_B_IMP, "ALL_W_1_AIR_B_IMP")
MAC(SURFER_ANIM_W_1_AIR_F_DIS, "ALL_W_1_AIR_F_DIS")
MAC(SURFER_ANIM_W_1_AIR_F_FRF, "ALL_W_1_AIR_F_FRF")
MAC(SURFER_ANIM_W_1_AIR_F_IMP, "ALL_W_1_AIR_F_IMP")
MAC(SURFER_ANIM_W_1_AIR_U_DIS, "ALL_W_1_AIR_U_DIS")
MAC(SURFER_ANIM_W_1_AIR_U_FRF, "ALL_W_1_AIR_U_FRF")
MAC(SURFER_ANIM_W_1_AIR_U_IMP, "ALL_W_1_AIR_U_IMP")
MAC(SURFER_ANIM_W_1_TTS_R_DIS, "ALL_W_1_TTS_R_DIS")
MAC(SURFER_ANIM_W_1_TTS_R_FRF, "ALL_W_1_TTS_R_FRF")
MAC(SURFER_ANIM_W_1_TTS_R_IMP, "ALL_W_1_TTS_R_IMP")
MAC(SURFER_ANIM_W_1_TTS_L_DIS, "ALL_W_1_TTS_L_DIS")
MAC(SURFER_ANIM_W_1_TTS_L_FRF, "ALL_W_1_TTS_L_FRF")
MAC(SURFER_ANIM_W_1_TTS_L_IMP, "ALL_W_1_TTS_L_IMP")
MAC(SURFER_ANIM_W_1_B_TUM, "ALL_W_1_B_TUM")
MAC(SURFER_ANIM_W_1_F_TUM, "ALL_W_1_F_TUM")
MAC(SURFER_ANIM_W_1_R_TUM, "ALL_W_1_R_TUM")
MAC(SURFER_ANIM_W_1_BR_TUM, "ALL_W_1_BR_TUM")
MAC(SURFER_ANIM_W_1_FR_TUM, "ALL_W_1_FR_TUM")
MAC(SURFER_ANIM_W_1_L_TUM, "ALL_W_1_L_TUM")
MAC(SURFER_ANIM_W_1_BL_TUM, "ALL_W_1_BL_TUM")
MAC(SURFER_ANIM_W_1_FL_TUM, "ALL_W_1_FL_TUM")
MAC(SURFER_ANIM_W_1_U_TUM, "ALL_W_1_U_TUM")
MAC(SURFER_ANIM_W_1_TTS_R_TUM, "ALL_W_1_TTS_R_TUM")
MAC(SURFER_ANIM_W_1_TTS_L_TUM, "ALL_W_1_TTS_L_TUM")
MAC(SURFER_ANIM_W_1_TUM_EXIT, "ALL_W_1_TUM_EXIT")
MAC(SURFER_ANIM_W_1_SWIM, "ALL_W_1_SWIM")
MAC(SURFER_ANIM_W_1_R_SWIM, "ALL_W_1_R_SWIM")
MAC(SURFER_ANIM_W_1_R_EOS, "ALL_W_1_R_EOS")
MAC(SURFER_ANIM_W_1_R_GOB, "ALL_W_1_R_GOB")
MAC(SURFER_ANIM_W_1_L_SWIM, "ALL_W_1_L_SWIM")
MAC(SURFER_ANIM_W_1_L_EOS, "ALL_W_1_L_EOS")
MAC(SURFER_ANIM_W_1_L_GOB, "ALL_W_1_L_GOB")
MAC(SURFER_ANIM_W_1_BAL_B_DIS, "ALL_W_1_BAL_B_DIS")
MAC(SURFER_ANIM_W_1_BAL_B_FRF, "ALL_W_1_BAL_B_FRF")
MAC(SURFER_ANIM_W_1_BAL_B_IMP, "ALL_W_1_BAL_B_IMP")
MAC(SURFER_ANIM_W_1_TAK_R_DIS, "ALL_W_1_TAK_R_DIS")
MAC(SURFER_ANIM_W_1_TAK_R_FRF, "ALL_W_1_TAK_R_FRF")
MAC(SURFER_ANIM_W_1_TAK_R_IMP, "ALL_W_1_TAK_R_IMP")
MAC(SURFER_ANIM_W_2_TAK_R_DIS, "ALL_W_2_TAK_R_DIS")
MAC(SURFER_ANIM_W_2_TAK_R_FRF, "ALL_W_2_TAK_R_FRF")
MAC(SURFER_ANIM_W_2_TAK_R_IMP, "ALL_W_2_TAK_R_IMP")
MAC(SURFER_ANIM_W_1_TAK_FLAT_WOBBLE, "ALL_W_1_TAK_FLAT_WOBBLE")
MAC(SURFER_ANIM_W_1_TAK_FLAT_DIS, "ALL_W_1_TAK_FLAT_DIS")
MAC(SURFER_ANIM_W_1_TAK_FLAT_FRF, "ALL_W_1_TAK_FLAT_FRF")
MAC(SURFER_ANIM_W_1_TAK_FLAT_IMP, "ALL_W_1_TAK_FLAT_IMP")
MAC(SURFER_ANIM_W_2_TRH_L_DIS, "ALL_W_2_TRH_L_DIS")
MAC(SURFER_ANIM_W_2_TRH_L_FRF, "ALL_W_2_TRH_L_FRF")
MAC(SURFER_ANIM_W_2_TRH_L_IMP, "ALL_W_2_TRH_L_IMP")
MAC(SURFER_ANIM_W_2_TRH_R_DIS, "ALL_W_2_TRH_R_DIS")
MAC(SURFER_ANIM_W_2_TRH_R_FRF, "ALL_W_2_TRH_R_FRF")
MAC(SURFER_ANIM_W_2_TRH_R_IMP, "ALL_W_2_TRH_R_IMP")
MAC(SURFER_ANIM_W_2_TRB_L_DIS, "ALL_W_2_TRB_L_DIS")
MAC(SURFER_ANIM_W_2_TRB_L_FRF, "ALL_W_2_TRB_L_FRF")
MAC(SURFER_ANIM_W_2_TRB_L_IMP, "ALL_W_2_TRB_L_IMP")
MAC(SURFER_ANIM_W_2_TRB_R_DIS, "ALL_W_2_TRB_R_DIS")
MAC(SURFER_ANIM_W_2_TRB_R_FRF, "ALL_W_2_TRB_R_FRF")
MAC(SURFER_ANIM_W_2_TRB_R_IMP, "ALL_W_2_TRB_R_IMP")
MAC(SURFER_ANIM_W_1_TAK_BACK_DIS, "ALL_W_1_TAK_BACK_DIS")
MAC(SURFER_ANIM_W_1_TAK_BACK_FRF, "ALL_W_1_TAK_BACK_FRF")
MAC(SURFER_ANIM_W_1_TAK_BACK_IMP, "ALL_W_1_TAK_BACK_IMP")
MAC(SURFER_ANIM_W_1_TAK_BACK_TUM, "ALL_W_1_TAK_BACK_TUM")

MAC(SURFER_ANIM_W_ENDOFSWIM, "ALL_W_ENDOFSWIM")

//  Bust through the tube animation.
MAC(SURFER_ANIM_TRK_TUBE_BUST_1, "ALL_TRK_TUBE_BUST_1")

//  Celebration / disappointment animations
MAC(SURFER_ANIM_BAS_CEL_01, "ALL_BAS_CEL_01")
MAC(SURFER_ANIM_BAS_DIS_01, "ALL_BAS_DIS_01")
MAC(SURFER_ANIM_BAS_CELNOT_01, "ALL_BAS_CELNOT_01")