/*  THIS FILE IS AUTOMATICALLY GENERATED BY EXPORT FROM THE EXCEL FILE:  SURFERDATA.XLS
    ALL CHANGES SHOULD BE MADE IN EXCEL AND RE_EXPORTED.  DO NOT HAND EDIT.
    David Cook, Treyarch, 6/25/01
*/

#ifndef SURFERDATA_H
#define SURFERDATA_H

enum {
    SURFER_BRUCE_IRONS,
    SURFER_DONAVON_FRANKENREITER,
    SURFER_KALANI_ROBB,
    SURFER_KELLY_SLATER,
    SURFER_LISA_ANDERSEN,
    SURFER_NATHAN_FLETCHER,
    SURFER_ROB_MACHADO,
    SURFER_TOM_CARROL,
    SURFER_TOM_CURREN,
    SURFER_MISC_SURFER,
    SURFER_TRAVIS_PASTRANA,
    SURFER_TIKI_GOD,
    SURFER_TONY_HAWK,
    SURFER_SURFREAK,
    SURFER_LAST
};

typedef struct SurferDataStruct {
    int start_stand;                             // First stand
    int start_turn;                              // First turn
    int start_carve;                             // First carve
    int start_anims;                             // First special
    int end_anims;                               // Last special
    int trickBook[70];                           // 
    int learnedtrickBook[16];                    // 
    char name[32];                               // Name
    char name_ps[32];                            // Personality Suit
    char stashfile[16];                          // Stash
    char firstname[32];                          // First Name
    char lastname[32];                           // Last Name
    char fullname[32];                           // Full name
    char abbr[4];                                // Abbreviation
    int goofy;                                   // Goofy footed
    int load_in_fe;                              // Temporary hack
    int bio_length;                              // Lines in Bio
    int has_movie;                               // Has a Movie
    int attr_spin;                               // Spin Attribute
    int attr_speed;                              // Speed Attribute
    int attr_balance;                            // Balance Attribute
    int attr_air;                                // Air Attribute
    char board_ent_name[20];                     // Board Entity Name
    char p_board_name[20];                       // Personality Board Name
    int selectable;                              // Selectable Character
    int competitor;                              // Does competitions?    (Deprecated)
    int initially_unlocked;                      // unlocked at start?
    char surfer_nick[20];                        // Surfer nickname (possesive)
    int sort_order;                              // Order they are drawn in FE
} SurferData, *SurferDataPtr;

extern SurferData SurferDataArray[];
extern const int TRICKBOOK_SIZE;
void SURFERDATA_Load(void);

#endif /* #ifndef SURFERDATA_H */
