/*  THIS FILE IS AUTOMATICALLY GENERATED BY EXPORT FROM THE EXCEL FILE:  WIPEOUTDATA.XLS
    ALL CHANGES SHOULD BE MADE IN EXCEL AND RE_EXPORTED.  DO NOT HAND EDIT.
    JONATHAN WEBSTER, Treyarch, 2/06/02
*/

#ifndef WIPEOUTDATA_H
#define WIPEOUTDATA_H

#include "types.h"
#include "VOEngine.h"
#include "globaltextenum.h"
#include "stringx.h"


#define SURFER_ANIM_NULL -1


const int DIR_DATA_FLAG = 0x00001;
const int BOARD_DIR_FLAG = 0x00002;
const int BOARD_RIGHT_FLAG = 0x00004;
const int MOM_DIR_FLAG = 0x00008;
const int MOM_ADDITIVE_FLAG = 0x00010;
const int DISMOUNT_NO_AIR_FLAG = 0x00020;
const int BOARD_NEG_DIR_FLAG = 0x00040;

enum {
    WIP_LOW_AIR_FOR,
    WIP_LOW_AIR_BACK,
    WIP_LOW_AIR_RIGHT,
    WIP_LOW_AIR_LEFT,
    WIP_LOW_AIR_FOR_RIGHT,
    WIP_LOW_AIR_FOR_LEFT,
    WIP_LOW_AIR_BOT_RIGHT,
    WIP_LOW_AIR_BOT_LEFT,
    WIP_LOW_HIT_BY_LIP,
    WIP_LOW_STUMBLE_BACK,
    WIP_LOW_LIE_FOR,
    WIP_LOW_LIE_FLAT,
    WIP_TAKE_OFF_FLAT,
    WIP_HIT_BY_CEILING_LEFT,
    WIP_HIT_BY_CEILING_RIGHT,
    WIP_HIT_BY_CEILING_FOR,
    WIP_HIT_BY_CEILING_BACK,
    WIP_TUBE_LOSE_BALANCE_LEFT,
    WIP_TUBE_LOSE_BALANCE_RIGHT,
    WIP_SLIDE_LOSE_BALANCE_RIGHT,
    WIP_SLIDE_LOSE_BALANCE_LEFT,
    WIP_NUM_TYPES
};

struct WipeoutData
{
    int wip_anim_dis;
    int wip_anim_free;
    int wip_anim_imp;
    int wip_anim_imp2;
    int wip_anim_trans;
    int wip_anim_swim;
    int b_wip_anim_dis;
    int b_wip_anim_free;
    int b_wip_anim_imp;
    int input_vel;
    float xvel;
    float yvel;
    float zvel;
    float dir_vel;
    int b_input_vel;
    float b_xvel;
    float b_yvel;
    float b_zvel;
    float b_dir_vel;
};


extern WipeoutData GWipeoutData[];

#endif /* #ifndef WIPEOUTDATA_H */
